// Generado a partir de countries-states-cities-database (dr5hn), filtrando por país
// el nivel administrativo con más entradas (provincia/estado/departamento/región según
// el país). No se actualiza automáticamente; si falta un país o queda desactualizado,
// hay que regenerarlo desde la misma fuente.
export const PROVINCES_BY_COUNTRY: Record<string, string[]> = {
  "AD": [
    "Acamparse",
    "Andorra la Vella",
    "Canillo",
    "Escaldes-Engordany",
    "La Massana",
    "Ordino",
    "Sant Julià de Lòria"
  ],
  "AE": [
    "Abu Dabi",
    "Ajmán",
    "Dubái",
    "Fujairah",
    "Ras Al Khaimah",
    "Sharjah",
    "Umm Al Quwain"
  ],
  "AF": [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balj",
    "Bamiyán",
    "Daykundi",
    "Farah",
    "Faryab",
    "Gazni",
    "Ghor",
    "Helmand",
    "Herat",
    "Jowzjan",
    "Kabul",
    "Kandahar",
    "Kapisa",
    "Khost",
    "Kunar",
    "Laghman",
    "Logar",
    "Nangarhar",
    "Nimruz",
    "Nuristán",
    "Paktia",
    "Paktika",
    "Panjshir",
    "Parwan",
    "Provincia de Kunduz",
    "Samangan",
    "Sar-e Pol",
    "Takhar",
    "Urozgán",
    "Wardak",
    "Zabul"
  ],
  "AG": [
    "San Felipe",
    "San Jorge",
    "San Juan",
    "San Pablo",
    "San Pedro",
    "Santa María"
  ],
  "AI": [
    "Colina del Norte",
    "Colina Sur",
    "El Barrio",
    "El Farrington",
    "El Valle",
    "Extremo este",
    "George Hill",
    "Lado Norte",
    "Puerto de la isla",
    "Punto de soplado",
    "Sandy Hill",
    "Suelo arenoso",
    "Terreno pedregoso",
    "West End"
  ],
  "AL": [
    "Ardiente",
    "Berat",
    "Dibër",
    "Durres",
    "Elbasan",
    "Gjirokastra",
    "Korçë",
    "Kukës",
    "Lezhë",
    "Shkodër",
    "Tirana",
    "Vlorë"
  ],
  "AM": [
    "Aragatsotn",
    "Ararat",
    "Armavir",
    "Gegharkunik",
    "Kotayk",
    "Lori",
    "Shirak",
    "Syunik",
    "Tavush",
    "Vayots Dzor"
  ],
  "AO": [
    "Bengo",
    "Benguela",
    "Bié",
    "Cabinda",
    "Cuando Cubango",
    "Cuanza",
    "Cuanza Norte",
    "Cunene",
    "Huambo",
    "Huila",
    "Luanda",
    "Lunda Norte",
    "Lunda Sur",
    "Malanje",
    "Moxico",
    "Namibe",
    "Uíge",
    "Zaire"
  ],
  "AR": [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán"
  ],
  "AS": [
    "Manuʻa",
    "Occidental",
    "Oriental"
  ],
  "AT": [
    "Alta Austria",
    "Baja Austria",
    "Burgenland",
    "Carintia",
    "Estiria",
    "Salsburgo",
    "Tirol",
    "Viena",
    "Vorarlberg"
  ],
  "AU": [
    "Australia del Sur",
    "Australia Occidental",
    "Nueva Gales del Sur",
    "Queensland",
    "Tasmania",
    "Victoria"
  ],
  "AW": [
    "Norte",
    "Oranjestad Este",
    "Oranjestad Oeste",
    "Paradera",
    "San Nicolás Norte",
    "San Nicolás Sur",
    "Santa Cruz",
    "Savaneta"
  ],
  "AX": [
    "Brändö",
    "Eckerö",
    "Finström",
    "Foglö",
    "Geta",
    "Hammarland",
    "Jomala",
    "Kökar",
    "Kumlinge",
    "Lemland",
    "Lumparland",
    "Mariehamn",
    "Saltvik",
    "Sottunga",
    "Sund",
    "Vårdö"
  ],
  "AZ": [
    "Absherón",
    "Agdam",
    "Agdash",
    "Aghyabadi",
    "Agstafa (ciudad)",
    "Aksu",
    "Astara",
    "Babek",
    "Balakan",
    "Barda (desambiguación)",
    "Bilasuvar",
    "Canguro",
    "Dashkasan",
    "Fizuli",
    "Gabala (ciudad)",
    "Gadabay",
    "Gazaj",
    "Gobustán",
    "Goranboy",
    "Goychay",
    "Goygol",
    "Guba",
    "Gubadli",
    "Ismailli",
    "Jalilabad",
    "Jizi (Azerbaiyán)",
    "Julfa",
    "Kalbayar",
    "Khachmaz",
    "Khojali",
    "Kürdəmir",
    "Lachín",
    "Lankaran (ciudad)",
    "Lerik",
    "Martuni",
    "Masally",
    "Neftcala",
    "Oğuz (desambiguación)",
    "Ordubad",
    "Raión de Beylagan",
    "Raión de Gaj",
    "Raión de Gusar",
    "Raión de Hayigabul",
    "Raión de Imishli",
    "Raión de Saatli",
    "Raión de Shabran",
    "Raión de Uyar",
    "Raión de Yardimli",
    "Raión de Zardab",
    "Sabirabad",
    "Sadarak",
    "Salyan",
    "Samuj",
    "Shahbuz",
    "Shaki",
    "Shamaji",
    "Shamkir",
    "Sharur",
    "Shusha",
    "Siazán",
    "Tartar (desambiguación)",
    "Tovuz",
    "Yabrayil",
    "Yevlax",
    "Zangilán",
    "Zaqatala"
  ],
  "BA": [
    "Federación de Bosnia y Herzegovina",
    "República Srpska"
  ],
  "BB": [
    "Iglesia de Cristo",
    "San Andrés",
    "San Felipe",
    "San Jorge",
    "San José",
    "San Juan",
    "San Miguel",
    "San Pedro",
    "Santa Lucía",
    "Santiago",
    "Santo Tomás"
  ],
  "BD": [
    "Bagerhat (zila)",
    "Bandarban (zila)",
    "Barguna (zila)",
    "Barisal (zila)",
    "Bhola (zila)",
    "Bogra (zila)",
    "Brahmanbaria (zila)",
    "Chandpur (zila)",
    "Chittagong (zila)",
    "Chuadanga (zila)",
    "Comilla (zila)",
    "Cox's Bazar (zila)",
    "Daca (zila)",
    "Dinajpur (zila)",
    "Faridpur (zila)",
    "Feni (zila)",
    "Gaibandha (zila)",
    "Gazipur (zila)",
    "Gopalganj",
    "Habiganj (zila)",
    "Jaipurhat (zila)",
    "Jamalpur (zila)",
    "Jessore (zila)",
    "Jhalokati (zila)",
    "Jhenaidah (zila)",
    "Khagrachari (zila)",
    "Khulna (zila)",
    "Kishoreganj (zila)",
    "Kurigram (zila)",
    "Kushtia (zila)",
    "Lakshmipur (zila)",
    "Lalmonirhat (zila)",
    "Madaripur (zila)",
    "Magura (zila)",
    "Manikganj (zila)",
    "Maulvibazar (zila)",
    "Meherpur (zila)",
    "Munshiganj (zila)",
    "Mymensingh (zila)",
    "Naogaon (zila)",
    "Narail (zila)",
    "Narayanganj (zila)",
    "Narsingdi (zila)",
    "Natore (zila)",
    "Nawabganj (zila)",
    "Netrokona (zila)",
    "Nilphamari (zila)",
    "Noakhali (zila)",
    "Pabna (zila)",
    "Panchagarh (zila)",
    "Patuakhali (zila)",
    "Pirojpur (zila)",
    "Rajbari (zila)",
    "Rajshahi (zila)",
    "Rangamati (zila)",
    "Rangpur (zila)",
    "Satkhira (zila)",
    "Shariatpur (zila)",
    "Sherpur (zila)",
    "Sirajganj (zila)",
    "Sunamganj (zila)",
    "Sylhet (zila)",
    "Tangail (zila)",
    "Thakurgaon (zila)"
  ],
  "BE": [
    "Amberes",
    "Brabante flamenco",
    "Brabante Valón",
    "Feudal",
    "Flandes Occidental",
    "Flandes Oriental",
    "Henao",
    "Limburgo",
    "Luxemburgo",
    "Namur"
  ],
  "BF": [
    "¡Bam!",
    "Bala",
    "Banwa",
    "Bazèga",
    "Bougouriba",
    "Boulgou",
    "Boulkiemde",
    "Comoé",
    "Ganzourgou",
    "Gnagna",
    "Gourma",
    "Houet",
    "Ioba",
    "Kadiogo",
    "Kénédougou",
    "Komondjari",
    "Kompienga",
    "Kossi",
    "Koulpélogo",
    "Kouritenga",
    "Kourwéogo",
    "Léraba",
    "Loroum",
    "Mouhoun",
    "Nahouri",
    "Nayala",
    "Nombre tenga",
    "Noumbiel",
    "Oubritenga",
    "Oudalan",
    "Passoré",
    "Poni",
    "Sanguié",
    "Sanmatenga",
    "Séno",
    "Sissili",
    "Soum",
    "Sourou",
    "Tapoa",
    "Tuy",
    "Yagha",
    "Yatenga",
    "Ziro",
    "Zondoma",
    "Zoundwéogo"
  ],
  "BG": [
    "Ardid",
    "Blagoevgrad",
    "Burgas",
    "Ciudad de Sofía",
    "Dobrich",
    "Gabrovo",
    "Haskovo",
    "Kardzhali",
    "Kyustendil",
    "Lovech",
    "Montana",
    "Pazardzhik",
    "Pernik",
    "Pleven",
    "Plovdiv",
    "Razgrad",
    "Shumen",
    "Silistra",
    "Sliven",
    "Smolyan",
    "Sofía",
    "Stara Zagora",
    "Targovishte",
    "Varna",
    "Veliko Tarnovo",
    "Vidin",
    "Vratsa",
    "Yambol"
  ],
  "BH": [
    "Capital",
    "Del norte",
    "Del sur",
    "Muharraq"
  ],
  "BI": [
    "Ayuntamiento de Bujumbura",
    "Bubanza",
    "Bujumbura Rural",
    "Bururi",
    "Cankuzo",
    "Cibitoke",
    "Gitega",
    "Karuzi",
    "Kayanza",
    "Kirundo",
    "Makamba",
    "Muramvya",
    "Muyinga",
    "Mwaro",
    "Ngozi",
    "Rumonge",
    "Rutana",
    "Ruyigi"
  ],
  "BJ": [
    "Alibori",
    "Atakora",
    "Atlántico",
    "Borgou",
    "Colinas",
    "Donga",
    "Kouffo",
    "Litoral",
    "Meseta",
    "Mononucleosis infecciosa",
    "Ouémé",
    "Zou"
  ],
  "BL": [
    "Saint-Barthélemy"
  ],
  "BM": [
    "De Smith",
    "Devonshire",
    "Hamilton",
    "Paget",
    "Pembroke",
    "San Jorge",
    "Sandys",
    "Southampton",
    "Warwick"
  ],
  "BN": [
    "Belait",
    "Brunei-Muara",
    "Temburong",
    "Tutong"
  ],
  "BO": [
    "Beni",
    "Chuquisaca",
    "Cochabamba",
    "La Paz",
    "Oruro",
    "Pando",
    "Potosí",
    "Santa Cruz",
    "Tarija"
  ],
  "BQ": [
    "Bonaire",
    "Saba",
    "San Eustaquio"
  ],
  "BR": [
    "Acre",
    "Alagoas",
    "Amapá",
    "Amazonas",
    "Bahía",
    "Ceará",
    "Espíritu Santo",
    "Goiás",
    "Maranhão",
    "Mato Grosso",
    "Mato Grosso del Sur",
    "Minas Gerais",
    "Paraca",
    "Paraíba",
    "Paraná",
    "Pernambuco",
    "Piauí",
    "Río de Janeiro",
    "Río Grande del Norte",
    "Río Grande del Sur",
    "Rondonia",
    "Roraima",
    "Santa Catarina",
    "São Paulo",
    "Sergipe",
    "Tocantins"
  ],
  "BS": [
    "Ábaco central",
    "Ábaco del Norte",
    "Acklins",
    "Andros central",
    "Andros del Norte",
    "Andros del Sur",
    "Bimini",
    "Cayo Mangrove",
    "Cayo Ron",
    "Ciudad de la esperanza",
    "Eleuthera central",
    "Eleuthera del Norte",
    "Eleuthera del Sur",
    "Exuma",
    "Gran Bahama Occidental",
    "Gran Bahama Oriental",
    "Gran Cayo",
    "Inagua",
    "Isla de Moore",
    "Isla de San Salvador",
    "Isla del Gato",
    "Isla Harbour",
    "Isla Ragged",
    "Isla Torcida",
    "Islas Berry",
    "Long Island",
    "Mayaguana",
    "Pozos españoles",
    "Puerto franco",
    "Punto negro",
    "Sur de Ábaco"
  ],
  "BT": [
    "Basura",
    "Bumthang",
    "Chukha",
    "Dagana",
    "Gasa",
    "Jaja",
    "Lhuntse",
    "Mongar",
    "Paro",
    "Pemagatshel",
    "Punakha",
    "Samdrup Jongkhar",
    "Samtse",
    "Sarpang",
    "Timbu",
    "Trashi Yangtse",
    "Trongsa",
    "Tsirang",
    "Wangdue Phodrang",
    "Zhemgang"
  ],
  "BW": [
    "Central",
    "Del sur",
    "Distrito de Chobe",
    "Ghanzi",
    "Kgalagadi",
    "Kgatleng",
    "Kweneng",
    "Nordeste",
    "Noroeste",
    "Sudeste"
  ],
  "BY": [
    "Brest",
    "Gómel",
    "Grodno",
    "Minsk",
    "Mogilev",
    "Vítebsk"
  ],
  "BZ": [
    "Belice",
    "Cayo",
    "Corozal",
    "Paseo Naranja",
    "Stann Creek",
    "Toledo"
  ],
  "CA": [
    "Alberta",
    "Columbia Británica",
    "Isla del Príncipe Eduardo",
    "Manitoba",
    "Nueva Escocia",
    "Nuevo Brunswick",
    "Ontario",
    "Quebec",
    "Saskatchewan",
    "Terranova y Labrador"
  ],
  "CD": [
    "Alto Katanga",
    "Alto Uélé",
    "Bajo Uélé",
    "Congo Central",
    "Ecuador",
    "Haut-Lomami",
    "Ituri",
    "Kasai",
    "Kasai Central",
    "Kasai Oriental",
    "Kivu del Norte",
    "Kivu del Sur",
    "Kwango",
    "Kwilu",
    "Lomami",
    "Lualaba",
    "Mai-Ndombe",
    "Maniema",
    "Mongala",
    "Sankuru",
    "Tanganica",
    "Tshopo",
    "Tshuapa",
    "Ubangi del Norte",
    "Ubangi del Sur"
  ],
  "CF": [
    "Alto Kotto",
    "Alto Mbomou",
    "Bamingui-Bangoran",
    "Basse-Kotto",
    "Kemo",
    "Lobaye",
    "Mambéré-Kadéï",
    "Mbomou",
    "Nana-Mambéré",
    "Ombella-M'Poko",
    "Ouaka",
    "Ouham",
    "Ouham-Pendé",
    "Sangha-Mbaéré",
    "Vakaga"
  ],
  "CG": [
    "Bouenza",
    "Brazzaville",
    "Cuvette-Ouest",
    "Kouilou",
    "Lékoumou",
    "Likouala",
    "Mesetas",
    "Niari",
    "Piscina",
    "Pointe-Noire",
    "Sangha",
    "Taza decorativa"
  ],
  "CH": [
    "Alfalfa",
    "Appenzell Rodas Exteriores",
    "Appenzell Rodas Interiores",
    "Argovia",
    "Basilea-Campiña",
    "Basilea-Ciudad",
    "Berna",
    "Friburgo",
    "Ginebra",
    "Glaris",
    "Grisones",
    "Jura",
    "Neuchâtel",
    "Nidwalden",
    "Obwalden",
    "San Galo",
    "Schaffhausen",
    "Schwyz",
    "Soleura",
    "Tesino",
    "Turgovia",
    "Uri",
    "Valais",
    "Vaud",
    "Zug",
    "Zúrich"
  ],
  "CI": [
    "Bas-Sassandra",
    "Comoé",
    "Denguelé",
    "Gôh-Yibua",
    "Lacas",
    "Lagunas",
    "Montañas",
    "Sabanas",
    "Sassandra-Marahoué",
    "Valle de Bandama",
    "Woroba",
    "Zanzan"
  ],
  "CL": [
    "Antofagasta",
    "Arica y Parinacota",
    "Atacama",
    "Aysén del General Carlos Ibáñez del Campo",
    "Biobío",
    "Coquimbo",
    "La Araucanía",
    "Libertador General Bernardo O'Higgins",
    "Los Lagos",
    "Los Ríos",
    "Magallanes y de la Antártica Chilena",
    "Maule",
    "Ñuble",
    "Región Metropolitana de Santiago",
    "Tarapacá",
    "Valparaíso"
  ],
  "CM": [
    "Adamawa",
    "Centro",
    "Este",
    "Extremo Norte",
    "Litoral",
    "Noroeste",
    "Norte",
    "Oeste",
    "Sur",
    "Suroeste"
  ],
  "CN": [
    "Anhui",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hubei",
    "Hunan",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanxi",
    "Sichuan",
    "Taiwán",
    "Yunnan",
    "Zhejiang"
  ],
  "CO": [
    "Amazonas",
    "Antioquia",
    "Arauca",
    "Atlántico",
    "Bolívar",
    "Boyacá",
    "Caldas",
    "Caquetá",
    "Casanare",
    "Cauca",
    "César",
    "Chocó",
    "Córdoba",
    "Cundinamarca",
    "Guainía",
    "Guaviare",
    "Huila",
    "La Guajira",
    "Magdalena",
    "Meta",
    "Nariño",
    "Norte de Santander",
    "Putumayo",
    "Quindío",
    "Risaralda",
    "San Andrés, Providencia y Santa Catalina",
    "Santander",
    "Sucre",
    "Tolima",
    "Valle del Cauca",
    "Vaupés",
    "Vichada"
  ],
  "CR": [
    "Alajuela",
    "Cartago",
    "Guanacaste",
    "Heredia",
    "Limón",
    "Puntarenas",
    "San José"
  ],
  "CU": [
    "Artemisa",
    "Camagüey",
    "Ciego de Ávila",
    "Cienfuegos",
    "Granma",
    "Guantánamo",
    "Holguín",
    "la Habana",
    "Las Tunas",
    "Matanzas",
    "Mayabeque",
    "Pinar del Río",
    "Sancti Spíritus",
    "Santiago de Cuba",
    "Villa Clara"
  ],
  "CV": [
    "Brava",
    "Buena Vista",
    "Mayo",
    "Monasterios",
    "Pablo",
    "Playa",
    "Porto Novo",
    "Ribeira Brava",
    "Ribeira Grande",
    "Ribeira Grande de Santiago",
    "Sal",
    "San Felipe",
    "San Miguel",
    "San Vicente",
    "Santa Catarina",
    "Santa Catarina do Fogo",
    "Santa Cruz",
    "Santo Domingo",
    "São Lourenço dos Órgãos",
    "São Salvador do Mundo",
    "Tarrafal",
    "Tarrafal de São Nicolau"
  ],
  "CY": [
    "Famagusta (Mağusa)",
    "Kyrenia (Keryneia)",
    "Larnaca (Larnaka)",
    "Limassol (Leymasun)",
    "Nicosia (Lefkoşa)",
    "Pafos (Pafos)"
  ],
  "CZ": [
    "Benešov",
    "Beroun",
    "Blansko",
    "Breclav",
    "Brno-město",
    "Brno-venkov",
    "Bruntál",
    "Česká Lípa",
    "České Budějovice",
    "Český Krumlov",
    "Cheb",
    "Chomutov",
    "Chrudim",
    "Cromo",
    "Děčín",
    "Domažlice",
    "Frýdek-Místek",
    "Havlíčkův Brod",
    "Hodonín",
    "Hradec Králové",
    "Jablonec nad Nisou",
    "Jeseník",
    "Jičín",
    "Jihlava",
    "Jindřichův Hradec",
    "Karlovy Vary",
    "Karviná",
    "Kladno",
    "Klatovy",
    "Kolín",
    "Kutná Hora",
    "Liberec",
    "Litoměřice",
    "Louny",
    "Mayoría",
    "Mělník",
    "Mladá Boleslav",
    "Náchod",
    "Nový Jičín",
    "Nymburk",
    "Olomouc",
    "Opava",
    "Ostrava-město",
    "Pardubice",
    "Pelhřimov",
    "Pilsen-jih",
    "Pilsen-sever",
    "Písek",
    "Plzeň-město",
    "Prachatice",
    "Praha-východ",
    "Praha-západ",
    "Preíbram",
    "Prerov",
    "Prostějov",
    "Rakovník",
    "Roca canina",
    "Rychnov nad Kněžnou",
    "Semily",
    "Sokolov",
    "Strakonice",
    "Šumperk",
    "Svitavy",
    "Tábor",
    "Tachov",
    "Teplice",
    "Třebíč",
    "Trutnov",
    "Uherské Hradiště",
    "Ústí nad Labem",
    "Ústí nad Orlicí",
    "Vsetín",
    "Vyškov",
    "Žďár nad Sázavou",
    "Zlín",
    "Znojmo"
  ],
  "DE": [
    "Baden-Württemberg",
    "Baja Sajonia",
    "Baviera",
    "Berlina",
    "Brandeburgo",
    "Bremen",
    "Hamburgo",
    "Hesse",
    "Mecklemburgo-Pomerania Occidental",
    "Renania del Norte-Westfalia",
    "Renania-Palatinado",
    "Sajonia",
    "Sajonia-Anhalt",
    "Sarre",
    "Schleswig-Holstein",
    "Turingia"
  ],
  "DJ": [
    "Ali Sabieh",
    "Artá",
    "Dikhil",
    "Obock",
    "Tadjourah"
  ],
  "DK": [
    "Dinamarca",
    "Dinamarca central",
    "Dinamarca del Norte",
    "Dinamarca meridional",
    "Zelanda"
  ],
  "DM": [
    "San Andrés",
    "San David",
    "San Jorge",
    "San José",
    "San Juan",
    "San Lucas",
    "San Marcos",
    "San Pablo",
    "San Patricio",
    "San Pedro"
  ],
  "DO": [
    "Azua",
    "Baoruco",
    "Barahona",
    "Dajabón",
    "Duarte",
    "El Seibo",
    "Elías Piña",
    "Espaillat",
    "Hato Mayor",
    "Hermanas Mirabal",
    "Independencia",
    "La Altagracia",
    "La Romana",
    "La Vega",
    "María Trinidad Sánchez",
    "Monseñor Nouel",
    "Monte Cristi",
    "Monte Plata",
    "Pedernales",
    "Peravia",
    "Puerto Plata",
    "Samaná",
    "San Cristóbal",
    "San José de Ocoa",
    "San Juan",
    "San Pedro de Macorís",
    "Sánchez Ramírez",
    "Santiago",
    "Santiago Rodríguez",
    "Santo Domingo",
    "Valverde"
  ],
  "DZ": [
    "Adrar",
    "Aïn Defla",
    "Aïn Témouchent",
    "Annaba",
    "Argel",
    "Batna",
    "Béchar",
    "Beni Abbès",
    "Biskra",
    "Blida",
    "Bordj Baji Mokhtar",
    "Bordj Bou Arréridj",
    "Bouira",
    "Boumerdès",
    "Bugía",
    "Chlef",
    "Constantino",
    "Djanet",
    "Djelfa",
    "El Bayadh",
    "El M'ghair",
    "El Menia",
    "El Oued",
    "El Tarf",
    "En Guezzam",
    "En Salah",
    "Ghardaïa",
    "Guelma",
    "Illizi",
    "Jenchela",
    "Jijel",
    "Laguna",
    "M'Sila",
    "Máscara",
    "Médéa",
    "Mila",
    "Mostaganem",
    "Nombre",
    "Orán",
    "Ouargla",
    "Ouled Djellal",
    "Oum El Bouaghi",
    "Relizane",
    "Saida",
    "Sétif",
    "Sidi Bel Abbès",
    "Skikda",
    "Tamanghasset",
    "Tébessa",
    "Tiaret",
    "Timimoun",
    "Tinduf",
    "Tipasa",
    "Tissemsilt",
    "Tizi Ouzou",
    "Tlemcen",
    "Touggourt",
    "Zoco Ahras"
  ],
  "EC": [
    "Azuay",
    "Bolívar",
    "Cañar",
    "Carchi",
    "Chimborazo",
    "Cotopaxi",
    "El Oro",
    "Esmeraldas",
    "Galápagos",
    "Guayas",
    "Imbabura",
    "Loja",
    "Los Ríos",
    "Manabí",
    "Morona Santiago",
    "Napo",
    "Orellana",
    "Pastaza",
    "Pichincha",
    "Santa Elena",
    "Santo Domingo de los Tsachilas",
    "Sucumbíos",
    "Tungurahua",
    "Zamora Chinchipe"
  ],
  "EE": [
    "Alutaguse",
    "Anija",
    "Häädemeeste",
    "Harku",
    "Hiiumaa",
    "Joelähtme",
    "Jõgeva",
    "Kehtna",
    "Kihnu",
    "Kiili",
    "Kohila",
    "Kose",
    "Kuusalu",
    "Lääne-Harju",
    "Lääne-Nigula",
    "Märjamaa",
    "Muhu",
    "Municipio de Antsla",
    "Municipio de Elva",
    "Municipio de Haljala",
    "Municipio de Järva",
    "Municipio de Kadrina",
    "Municipio de Kambja",
    "Municipio de Kanepi",
    "Municipio de Kastre",
    "Municipio de Lääneranna",
    "Municipio de Luunja",
    "Municipio de Mulgi",
    "Municipio de Mustvee",
    "Municipio de Nõo",
    "Municipio de Otepää",
    "Municipio de Peipsiääre",
    "Municipio de Põhja-Sakala",
    "Municipio de Põlva",
    "Municipio de Rakvere",
    "Municipio de Räpina",
    "Municipio de Rõuge",
    "Municipio de Saarde",
    "Municipio de Setomaa",
    "Municipio de Tapa",
    "Municipio de Tartu",
    "Municipio de Tori",
    "Municipio de Tõrva",
    "Municipio de Türi",
    "Municipio de Valga",
    "Municipio de Viljandi",
    "Municipio de Vinni",
    "Municipio de Viru-Nigula",
    "Municipio de Võru",
    "Parroquia de Jõhvi",
    "Parroquia de Lüganuse",
    "Põhja-Pärnu",
    "Poltsamaa",
    "Raasiku",
    "Rae (Estonia)",
    "Rapla",
    "Ruhnu",
    "Saaremaa",
    "Saku (Estonia)",
    "Salsa",
    "Toila",
    "Väike-Maarja",
    "Viimsi",
    "Vormsi"
  ],
  "EG": [
    "Alejandría",
    "Asiut",
    "Asuán",
    "Beheira",
    "Beni Suef",
    "Caliubia",
    "Dakahlia",
    "Damieta",
    "El Cairo",
    "Fayum",
    "Gharbia",
    "Giza",
    "Ismailía",
    "Kafr El-Sheikh",
    "Luxor",
    "Mar Rojo",
    "Matruh",
    "Minya",
    "Monufia",
    "Nuevo Valle",
    "Puerto Said",
    "Quena",
    "Sharqia",
    "Sinaí del Norte",
    "Sinaí del Sur",
    "Suez",
    "Suhag"
  ],
  "ER": [
    "Anseba",
    "Descomprimir",
    "Gash-Barka",
    "Maekel",
    "Mar Rojo meridional",
    "Norte del Mar Rojo"
  ],
  "ES": [
    "A Coruña",
    "Albacete",
    "Alicante",
    "Almería",
    "Araba",
    "Asturias",
    "Ávila",
    "Badajoz",
    "Barcelona",
    "Bizkaia",
    "Burgos",
    "Cáceres",
    "Cádiz",
    "Cantabria",
    "Castellón",
    "Ciudad Real",
    "Córdoba",
    "Cuenca",
    "Gerona",
    "Gipuzkoa",
    "Granada",
    "Guadalajara",
    "Huelva",
    "Huesca",
    "Islas Baleares",
    "Jaén",
    "La Rioja",
    "Las Palmas",
    "León",
    "Lérida",
    "Lugo",
    "Madrid",
    "Málaga",
    "Murcia",
    "Navarra",
    "Orense",
    "Palencia",
    "Pontevedra",
    "Salamanca",
    "Santa Cruz de Tenerife",
    "Segovia",
    "Sevilla",
    "Soria",
    "Tarragona",
    "Teruel",
    "Toledo",
    "Valencia",
    "Valladolid",
    "Zamora",
    "Zaragoza"
  ],
  "ET": [
    "Amhara",
    "Benishangul-Gumuz",
    "Gambela",
    "Harari",
    "Lejos",
    "Naciones, nacionalidades y pueblos del Sur",
    "Oromía",
    "Pueblos del suroeste de Etiopía",
    "Sidama",
    "somalí",
    "Tigray"
  ],
  "FI": [
    "Carelia del Norte",
    "Finlandia central",
    "Finlandia propiamente dicha",
    "Kainuu",
    "Karelia del Sur",
    "Kymenlaakso",
    "Laponia",
    "Ostrobotnia",
    "Ostrobotnia Central",
    "Ostrobotnia del Norte",
    "Ostrobotnia del Sur",
    "Päijänne Tavastia",
    "Pirkanmaa",
    "Satakunta",
    "Savonia del Norte",
    "Savonia del Sur",
    "Tavastia propiamente dicha",
    "Uusimaa"
  ],
  "FJ": [
    "Bua",
    "Cakaudrove",
    "Kadavu",
    "Lau",
    "Licenciado en Letras",
    "Lomaiviti",
    "Macuata",
    "Nadroga-Navosa",
    "Naitasiri",
    "Namosi",
    "Real academia de bellas artes",
    "Rewa",
    "Serua",
    "Tailevu"
  ],
  "FM": [
    "Chuuk",
    "Kosrae",
    "Ladrar",
    "Pohnpei"
  ],
  "FO": [
    "Eysturoy",
    "Islas del Norte",
    "Sandoy",
    "Streymoy",
    "Suðuroy",
    "Vágar"
  ],
  "FR": [
    "Ain",
    "Aisne",
    "Allier",
    "Alpes de Alta Provenza",
    "Alpes Marítimos",
    "Alta Córcega",
    "Alta Saboya",
    "Alto Garona",
    "Alto Loira",
    "Alto Marne",
    "Alto Rin",
    "Alto Saona",
    "Alto Vienne",
    "Altos Alpes",
    "Altos del Sena",
    "Altos Pirineos",
    "Ardèche",
    "Ardenas",
    "Ariège",
    "Aube",
    "Aude",
    "Aveyron",
    "Bajo Rin",
    "Bocas del Ródano",
    "Calvados",
    "Cantal",
    "Charente",
    "Charente Marítimo",
    "Córcega del Sur",
    "Correze",
    "Costa de Oro",
    "Costas de Armor",
    "Creuse",
    "Deux-Sèvres",
    "Dordoña",
    "Drôme",
    "Dudas",
    "Essonne",
    "Eure",
    "Eure y Loir",
    "Finisterre",
    "Gers",
    "Gironda",
    "Guardia",
    "Hérault",
    "Ille y Vilaine",
    "Indre",
    "Indre y Loira",
    "Isère",
    "Jura",
    "Landas",
    "Loir-et-Cher",
    "Loira",
    "Loira Atlántico",
    "Loiret",
    "Lot y Garona",
    "Lote",
    "Lozère",
    "Maine y Loira",
    "Mancha",
    "Marne",
    "Mayenne",
    "Meurthe y Mosela",
    "Morbihan",
    "Mosa",
    "Mosela",
    "Nièvre",
    "Norte",
    "Oise",
    "Orne",
    "Paso de Calais",
    "Pirineos Atlánticos",
    "Pirineos Orientales",
    "Puy-de-Dôme",
    "Querida",
    "Ródano",
    "Saboya",
    "Saona y Loira",
    "Sarthe",
    "Sena Marítimo",
    "Sena y Marne",
    "Sena-Saint-Denis",
    "Somme",
    "Tarn",
    "Tarn y Garona",
    "Territorio de Belfort",
    "Valle del Marne",
    "Valle del Oise",
    "Var",
    "Vaucluse",
    "Vendée",
    "Viena",
    "Vosgos",
    "Yonne",
    "Yvelines"
  ],
  "GA": [
    "Alto Ogooué",
    "Estuario",
    "Medio Ogooué",
    "Ngounié",
    "Nyanga",
    "Ogooué-Ivindo",
    "Ogooué-Lolo",
    "Ogooué-Marítimo",
    "Woleu-Ntem"
  ],
  "GB": [
    "Bath y el noreste de Somerset",
    "Bedford",
    "Bedfordshire central",
    "Berkshire Occidental",
    "Blackburn con Darwen",
    "Blackpool",
    "Blaenau Gwent",
    "Bosque de Bracknell",
    "Bournemouth, Christchurch y Poole",
    "Bridgend",
    "Brighton y Hove",
    "Brístol",
    "Buckinghamshire",
    "Caerphilly",
    "Cardiff",
    "Carmarthenshire",
    "Ceredigion",
    "Cheshire Este",
    "Cheshire Oeste y Chester",
    "Ciudad de Kingston upon Hull",
    "Ciudad de Southampton",
    "Conwy",
    "Cornualles",
    "Darlington",
    "Denbighshire",
    "derby",
    "Durham",
    "East Riding de Yorkshire",
    "Flintshire",
    "Gloucestershire del Sur",
    "Gwynedd",
    "Halton",
    "Hartlepool",
    "Herefordshire",
    "Isla de Anglesey",
    "Isla de Wight",
    "Islas Sorlingas",
    "Lectura",
    "Leicester",
    "Luton",
    "Medway",
    "Merthyr Tydfil",
    "Middlesbrough",
    "Milton Keynes",
    "Monmouthshire",
    "Mudar",
    "Neath Port Talbot",
    "Newport",
    "Noreste de Lincolnshire",
    "Norte de Lincolnshire",
    "Norte de Northamptonshire",
    "Norte de Somerset",
    "Northamptonshire occidental",
    "Northumberland",
    "Nottingham",
    "Pembrokeshire",
    "Peterborough",
    "Plymouth",
    "Portsmouth",
    "Powys",
    "Redcar y Cleveland",
    "Rhondda Cynon Taf",
    "Rutland",
    "Shropshire",
    "Southend-on-Sea",
    "Stockton-on-Tees",
    "Stoke-on-Trent",
    "Swansea",
    "Swindon",
    "Telford y Wrekin",
    "Thurrock",
    "Torbay",
    "Torfaen",
    "Valle de Glamorgan",
    "Warrington",
    "Wiltshire",
    "Windsor y Maidenhead",
    "Wokingham",
    "Wrexham",
    "York"
  ],
  "GD": [
    "San Andrés",
    "San David",
    "San Jorge",
    "San Juan",
    "San Marcos",
    "San Patricio"
  ],
  "GE": [
    "Guria",
    "Imereti",
    "Kajetia",
    "Kvemo Kartli",
    "Mtskheta-Mtianeti",
    "Racha-Lechkhumi y Kvemo Svaneti",
    "Samegrelo-Zemo Svaneti",
    "Samtskhe-Yavakheti",
    "Shida Kartli"
  ],
  "GF": [
    "Guyane"
  ],
  "GG": [
    "Alderney",
    "Bosque",
    "Castillo",
    "Puerto de San Pedro",
    "San Andrés",
    "San Martín",
    "San Pedro del Bosque",
    "San Salvador",
    "San Sansón",
    "Sark",
    "Torteval",
    "Valle"
  ],
  "GH": [
    "Ahafo",
    "Alto Oeste",
    "Alto Oriente",
    "Ashanti",
    "Bono",
    "Bono Este",
    "Central",
    "Del norte",
    "Gran Accra",
    "Noreste",
    "Norte occidental",
    "Occidental",
    "Oriental",
    "Oti",
    "Sabana",
    "Vuelta"
  ],
  "GL": [
    "Avannaata",
    "Kujalleq",
    "Qeqertalik",
    "Qeqqata",
    "Sermersooq"
  ],
  "GM": [
    "Banco Norte",
    "Costa Oeste",
    "Río Central",
    "Río Inferior",
    "Río superior"
  ],
  "GN": [
    "Agave",
    "Beyla",
    "Boffa",
    "Boké",
    "Coyah",
    "Dabola",
    "Dalaba",
    "Dinguiraye",
    "Dubreka",
    "Faranah",
    "Forécariah",
    "Fría",
    "Gaual",
    "Guéckédou",
    "Kankan",
    "Kérouané",
    "Kindia",
    "Kissidougou",
    "Koubia",
    "Koundara",
    "Kouroussa",
    "Labé",
    "Lélouma",
    "Lola",
    "Macenta",
    "Malí",
    "Mamou",
    "Mandiana",
    "Nzérékoré",
    "Siguiri",
    "Télimélé",
    "Tougué",
    "Yomo"
  ],
  "GP": [
    "Basse-Terre",
    "Pointe-à-Pitre"
  ],
  "GQ": [
    "Annobón",
    "Bioko Norte",
    "Bioko Sur",
    "Centro Sur",
    "Kié-Ntem",
    "Litoral",
    "Provincia de Djibloho",
    "Wele-Nzas"
  ],
  "GR": [
    "Ática",
    "Creta",
    "Egeo meridional",
    "Egeo septentrional",
    "Epiro",
    "Grecia central",
    "Grecia Occidental",
    "Islas Jónicas",
    "Macedonia Central",
    "Macedonia Occidental",
    "Macedonia Oriental y Tracia",
    "Peloponeso",
    "Tesalia"
  ],
  "GT": [
    "Alta Verapaz",
    "Baja Verapaz",
    "Chimaltenango",
    "Chiquimula",
    "El Progreso",
    "Escuintla",
    "Guatemala",
    "Huehuetenango",
    "Izabal",
    "Jalapa",
    "Jutiapa",
    "Petén",
    "Quetzaltenango",
    "Quiché",
    "Retalhuleu",
    "Sacatepéquez",
    "San Marcos",
    "Santa Rosa",
    "Sololá",
    "Suchitepéquez",
    "Totonicapán",
    "Zacapa"
  ],
  "GU": [
    "Agarrar",
    "Alturas de Agana",
    "Asan-Maina",
    "Barrigada",
    "Chalan Pago-Ordot",
    "Dededo",
    "Hagaña",
    "Inarajan (Inalåhan)",
    "Mangilao",
    "Merizo (Malesso)",
    "Mongmong-Toto-Maite",
    "Piti",
    "Santa Rita (Sånta Rita-Sumai)",
    "Sinajana",
    "Talofofo (Talo'fo'fo)",
    "Tamuning",
    "Umatac (Humåtak)",
    "yigo",
    "Yona"
  ],
  "GW": [
    "Bafatá",
    "Biombo",
    "Bolama",
    "Cacheu",
    "Gabú",
    "Oio",
    "Quinara",
    "Tombali"
  ],
  "GY": [
    "Alto Demerara-Berbice",
    "Alto Takutu-Alto Esequibo",
    "Barima-Waini",
    "Berbice Oriental-Corentyne",
    "Cuyuni-Mazaruni",
    "Demerara-Mahaica",
    "Islas Esequibo-Demerara Occidental",
    "Mahaica-Berbice",
    "Pomeroon-Supenaam",
    "Potaro-Siparuni"
  ],
  "HK": [
    "Central y Occidental",
    "Ciudad de Kowloon",
    "Del sur",
    "Islas",
    "Kwai Tsing",
    "Kwun Tong",
    "Norte",
    "Oriental",
    "Sai Kung",
    "Sha Tin",
    "Sham Shui Po",
    "Tai Po",
    "Tsuen Wan",
    "Tuen Mun",
    "Wan Chai",
    "Wong Tai Sin",
    "Yau Tsim Mong",
    "Yuen Long"
  ],
  "HN": [
    "Atlántida",
    "Choluteca",
    "Colon",
    "Comayagua",
    "Copán",
    "Cortés",
    "El Paraíso",
    "Francisco Morazán",
    "Gracias a Dios",
    "Intibucá",
    "Islas de la Bahía",
    "La Paz",
    "Lempira",
    "Ocotepeque",
    "Olancho",
    "Santa Bárbara",
    "Valle",
    "Yoro"
  ],
  "HR": [
    "Bjelovar-Bilogora",
    "Brod-Posavina",
    "Dubrovnik-Neretva",
    "Istria",
    "Karlovac",
    "Koprivnica-Križevci",
    "Krapina-Zagorje",
    "Lika-Senj",
    "Međimurje",
    "Osijek-Baranja",
    "Požega-Eslavonia",
    "Primorje-Gorski Kotar",
    "Šibenik-Knin",
    "Sisak-Moslavina",
    "Split-Dalmacia",
    "Varaždin",
    "Virovitica-Podravina",
    "Vukovar-Syrmia",
    "Zadar",
    "Zagreb"
  ],
  "HT": [
    "Artibonite",
    "Centro",
    "Grand'Anse",
    "Nordeste",
    "Noroeste",
    "Norte",
    "Oeste",
    "Pezones",
    "Sur",
    "Sureste"
  ],
  "HU": [
    "Békéscsaba",
    "Debrecen",
    "Dunaújváros",
    "Eger",
    "Érd",
    "Győr",
    "Hódmezővásárhely",
    "Kaposvár",
    "Kecskemét",
    "Miskolc",
    "Nagykanizsa",
    "Nyíregyháza",
    "Pécs",
    "Salgótarján",
    "Sopron",
    "Szeged",
    "Székesfehérvár",
    "Szekszárd",
    "Szolnok",
    "Szombathely",
    "Tatabánya",
    "Veszprém"
  ],
  "ID": [
    "Aceh",
    "Bali",
    "Bantén",
    "Bengkulu",
    "Gorontalo",
    "Islas Riau",
    "Jambi",
    "Jawa Barat",
    "Jawa Tengah",
    "Jawa Timur",
    "Kalimantan Barat",
    "Kalimantan Selatan",
    "Kalimantan Tengah",
    "Kalimantan Timur",
    "Kalimantan Utara",
    "Kepulauan Bangka Belitung",
    "Lampung",
    "Maluku Utara",
    "Molucas",
    "Nusa Tenggara Barat",
    "Nusa Tenggara Timur",
    "Papúa Barat",
    "Papúa Barat Daya",
    "Papúa Nueva Guinea",
    "Papúa Pegunungan",
    "Papúa Tengah",
    "Papuasia",
    "Riau",
    "Sulawesi Barat",
    "Sulawesi Selatan",
    "Sulawesi Tenggara",
    "Sulawesi Utara",
    "Sumatra Barat",
    "Sumatra Selatan",
    "Sumatra Utara",
    "Tengah de Sulawesi"
  ],
  "IE": [
    "Carlow",
    "Cavan",
    "Clara",
    "Corcho",
    "Donegal",
    "Dublín",
    "Galway",
    "Kerry",
    "Kildare",
    "Kilkenny",
    "Laois",
    "Leitrim",
    "Longford",
    "Louth",
    "Mayonesa",
    "Meath",
    "Monaghan",
    "Offaly",
    "Quintilla cómica",
    "Roscommon",
    "Sligo",
    "Tipperary",
    "Waterford",
    "Westmeath",
    "Wexford",
    "Wicklow"
  ],
  "IL": [
    "Central",
    "Del norte",
    "Del sur",
    "Haifa",
    "Jerusalén",
    "Tel Aviv"
  ],
  "IM": [
    "Ayre",
    "Garff",
    "Glenfaba",
    "Medio",
    "Miguel",
    "Rushen"
  ],
  "IN": [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bengala Occidental",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagalandia",
    "Odisha",
    "Punjab",
    "Rajastán",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand"
  ],
  "IQ": [
    "Al Anbar",
    "Al Muthanna",
    "Al-Qādisiyyah",
    "Babilonia",
    "Bagdad",
    "Basora",
    "Dhi Qar",
    "Diyala",
    "Dohuk",
    "Erbil",
    "Karbala",
    "Kirkuk",
    "Maysan",
    "Nayaf",
    "Nínive",
    "Saladino",
    "Suleimaniya",
    "Wasit"
  ],
  "IR": [
    "Alborz",
    "Ardabil",
    "Azerbaiyán Occidental",
    "Azerbaiyán Oriental",
    "Bushehr",
    "Chaharmahal y Bakhtiari",
    "Gilán",
    "Golestán",
    "Hamadán",
    "Hormozgán",
    "Ilam",
    "Isfahán",
    "Jorasán del Norte",
    "Jorasán del Sur",
    "Jorasán Razavi",
    "Juzestán",
    "Kermán",
    "Kermanshah",
    "Kohgiluyeh y Boyer-Ahmad",
    "Kurdistán",
    "Lejos",
    "Lorestán",
    "Markazi",
    "Mazandarán",
    "Qazvín",
    "Qom",
    "Semnan",
    "Sistán y Baluchistán",
    "Teherán",
    "Yazd",
    "Zanjan"
  ],
  "IS": [
    "Akranes",
    "Akureyri",
    "Árborg",
    "Árneshreppur",
    "Ásahreppur",
    "Bláskógabyggð",
    "Bolungarvík",
    "Borgarbyggð",
    "Dalabyggð",
    "Dalvíkurbyggð",
    "Eyja- og Miklaholtshreppur",
    "Eyjafjarðarsveit",
    "Fjallabyggð",
    "Fjarðabyggð",
    "Fljótsdalshreppur",
    "Flóahreppur",
    "Garðabær",
    "Grímsnes- og Grafningshreppur",
    "Grindavík",
    "Grundarfjörður",
    "Grýtubakkahreppur",
    "Hafnarfjörður",
    "Hörðarsveit",
    "Hornafjörður",
    "Hrunamannahreppur",
    "Húnabyggð",
    "Húnaþing Vestra",
    "Hvalfjarðarsveit",
    "Hveragerði",
    "Ísafjörður",
    "Islas Vestman",
    "Kaldrananeshreppur",
    "Kjósarhreppur",
    "Kópavogur",
    "Langanesbyggð",
    "Mosfellsbær",
    "Múlaþing",
    "Municipio de Reykjanesbær",
    "Mýrdalshreppur",
    "Norðurþing",
    "Rangárþing Eystra",
    "Rangárþing ytra",
    "Reikiavik",
    "Reykhólahreppur",
    "Seltjarnarnes",
    "Skaftárhreppur",
    "Skagabyggð",
    "Skagafjörður (fiordo)",
    "Skagaströnd",
    "Skeiða- og Gnúpverjahreppur",
    "Skorradalshreppur",
    "Snæfellsbær",
    "Strandabyggð",
    "Stykkishólmur",
    "Súðavík",
    "Suðurnesjabær",
    "Svalbarðsstrandarhreppur",
    "Sveitarfélagið Ölfus",
    "Tálknafjörður",
    "Tjörneshreppur",
    "Vesturbyggð",
    "Vogar",
    "Vopnafjörður",
    "Þingeyjarsveit"
  ],
  "IT": [
    "Alejandría",
    "Ancona",
    "Arezzo",
    "Ascoli Piceno",
    "Asti",
    "Avellino",
    "Barletta-Andria-Trani",
    "Belluno",
    "Benevento",
    "Bérgamo",
    "Biella",
    "Brescia",
    "Brindisi",
    "Campobasso",
    "Caserta",
    "Catanzaro",
    "Chieti",
    "Como",
    "Cosenza",
    "Cremona",
    "Crotona",
    "Cúneo",
    "Fermo",
    "Ferrara",
    "Foggia",
    "Forlì-Cesena",
    "Frosinona",
    "Grosseto",
    "Imperio",
    "Isernia",
    "L'Aquila",
    "La Spezia",
    "Latina",
    "Lecce",
    "Lecco",
    "Livorno",
    "Lodi",
    "Lucca",
    "Macerata",
    "Mantua",
    "Massa y Carrara",
    "Matera",
    "Módena",
    "Monza y Brianza",
    "Novara",
    "Nuoro",
    "Oristán",
    "Padua",
    "Parma",
    "Pavía",
    "Perugia",
    "Pesaro y Urbino",
    "Pescara",
    "Pisa",
    "Pistoia",
    "Plasencia",
    "Potenza",
    "Prato",
    "Rávena",
    "Reggio Emilia",
    "Rieti",
    "Rímini",
    "Rovigo",
    "Salerno",
    "Sassari",
    "Savona",
    "Siena",
    "Sondrio",
    "Sur de Cerdeña",
    "Taranto",
    "Teramo",
    "Terni",
    "Treviso",
    "Varese",
    "Verbano-Cusio-Ossola",
    "Vercelli",
    "Verona",
    "Vibo Valentia",
    "Vicenza",
    "Viterbo"
  ],
  "JE": [
    "Grouville",
    "San Clemente",
    "San Juan",
    "San Lorenzo",
    "San Martín",
    "San Ouen",
    "San Pedro",
    "San Salvador",
    "Santa Brelade",
    "Santa María",
    "St. Helier",
    "Trinidad"
  ],
  "JM": [
    "Hanovre",
    "Kingston",
    "Letras gruesas a la media",
    "Manchester",
    "Portland",
    "San Andrés",
    "Santa Ana",
    "Santa Catalina",
    "Santa Isabel",
    "Santa María",
    "Santiago",
    "Santo Tomás",
    "Trelawny",
    "Westmoreland"
  ],
  "JO": [
    "Ajloun",
    "Ammán",
    "Áqaba",
    "Balqa",
    "Irbid",
    "Jerash",
    "Karak",
    "Ma'an",
    "Madaba",
    "Mafraq",
    "Tafila",
    "Zarqa"
  ],
  "JP": [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyōgo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kioto",
    "kochi",
    "Kumamoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokio",
    "Tokushima",
    "totori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi"
  ],
  "KE": [
    "Bahía de Homa",
    "Baringo",
    "Bomet",
    "Bungoma",
    "Busia",
    "Ciudad de Nairobi",
    "Elgeyo-Marakwet",
    "Embú",
    "Garissa",
    "Isiolo",
    "Kajiado",
    "kakamega",
    "Kericho",
    "Kiambu",
    "Kilifi",
    "Kirinyaga",
    "Kisii",
    "Kisumu",
    "Kitui",
    "Kwale",
    "Laikipia",
    "Lamu",
    "Machakos",
    "Makueni",
    "Mandera",
    "Marsabit",
    "Meru",
    "Migori",
    "Mombasa",
    "Murang'a",
    "Nakuru",
    "Nandi",
    "Narok",
    "Nyamira",
    "Nyandarua",
    "Nyeri",
    "Pokot occidental",
    "Río Tana",
    "Samburu",
    "Siaya",
    "Taita–Taveta",
    "Tharaka-Nithi",
    "Trans Nzoia",
    "Turkana",
    "Uasin Gishu",
    "Vihiga",
    "Wajir"
  ],
  "KG": [
    "Batken",
    "Chuy",
    "Issyk-Kul",
    "Jalal-Abad",
    "Naryn",
    "Osh",
    "Talas"
  ],
  "KH": [
    "Banteay Meanchey",
    "Battambang",
    "Kampong Cham",
    "Kampong Chhnang",
    "Kampong Speu",
    "Kampong Thom",
    "Kampot",
    "Kandal",
    "Koh Kong",
    "Kratie",
    "Mantener",
    "Mondulkiri",
    "Oddar Meanchey",
    "Pailín",
    "Preah Vihear",
    "Presa Veng",
    "Pursat",
    "Ratanakiri",
    "Siem Reap",
    "Sihanoukville",
    "Stung Treng",
    "Svay Rieng",
    "Takeo",
    "Tboung Khmum"
  ],
  "KI": [
    "Fénix",
    "Gilbert",
    "Línea"
  ],
  "KM": [
    "Anjouan",
    "Gran Comora",
    "Mohéli"
  ],
  "KN": [
    "Iglesia de Cristo Nichola Town",
    "Isla central de Santo Tomás",
    "Punta Palmetto de la Trinidad",
    "Punta Sandy de Santa Ana",
    "San Jorge Basseterre",
    "San Jorge Gingerland",
    "San Juan Capisterre",
    "San Juan Higuera",
    "San Pablo Capisterre",
    "San Pablo Charlestown",
    "San Pedro Basseterre",
    "Santa María Cayón",
    "Santiago Barlovento",
    "Tierras bajas de Santo Tomás"
  ],
  "KP": [
    "Chagang",
    "Hamgyong del Norte",
    "Hamgyong del Sur",
    "Hwanghae del Norte",
    "Hwanghae del Sur",
    "Kangwon",
    "Pyongan del Norte",
    "Pyongan del Sur",
    "Ryanggang"
  ],
  "KR": [
    "Chungcheong del Norte",
    "Chungcheong del Sur",
    "Gyeonggi",
    "Gyeongsang del Norte",
    "Gyeongsang del Sur",
    "Jeolla del Norte",
    "Jeolla del Sur"
  ],
  "KW": [
    "Al Ahmadi",
    "Al Asimah",
    "Al Farwaniyah",
    "Al Jahra",
    "Hawái",
    "Mubarak Al-Kabeer"
  ],
  "KY": [
    "Caimán Brac",
    "Gran Caimán",
    "Pequeño Caimán"
  ],
  "KZ": [
    "Abai",
    "Akmola",
    "Aktobe",
    "Almaty",
    "Atyrau",
    "Jambyl",
    "Jetisu",
    "Karagandá",
    "Kazajstán Occidental",
    "Kazajstán Oriental",
    "Kostanái",
    "Kyzylorda",
    "Mangystau",
    "norte de Kazajstán",
    "Pavlodar",
    "Turkestán",
    "Ulytau"
  ],
  "LA": [
    "Attapeu",
    "Bokeo",
    "Bolikhamsai",
    "Champasak",
    "Houaphanh",
    "Khammouane",
    "Luang Namtha",
    "Luang Prabang",
    "Oudomxay",
    "Phongsaly",
    "Sainyabuli",
    "Salavan",
    "Savannakhet",
    "Sekong",
    "Vientián",
    "Xaisomboun",
    "Xiangkhouang"
  ],
  "LB": [
    "Akkar",
    "Baalbek-Hermel",
    "Becá",
    "Beirut",
    "Monte Líbano",
    "Nabatieh",
    "Norte",
    "Sur"
  ],
  "LC": [
    "Anse la Raye",
    "Canarias",
    "Castries",
    "Dennery",
    "Elección",
    "Islote Gros",
    "Laborie",
    "Micoud",
    "Soufrière",
    "Viejo Fuerte"
  ],
  "LI": [
    "Balzers",
    "Eschen",
    "Gamprin",
    "Mauren",
    "Planken",
    "Ruggell",
    "Schaan",
    "Schellenberg",
    "Triesen",
    "Triesenberg",
    "Vaduz"
  ],
  "LK": [
    "Ampara",
    "Anuradhapura",
    "Badulla",
    "Batticaloa",
    "Colombo",
    "Galle",
    "Gampaha",
    "Hambantota",
    "Jaffna",
    "Kalutara",
    "Kandy",
    "Kegalle",
    "Kilinochchi",
    "Kurunegala",
    "Mannar",
    "Matale",
    "Matara",
    "Monaragala",
    "Mullaitivu",
    "Nuwara Eliya",
    "Polonnaruwa",
    "Puttalam",
    "Ratnapura",
    "Trincomalee",
    "Vavuniya"
  ],
  "LR": [
    "Bomi",
    "Bong",
    "Cess del río",
    "Gbarpolu",
    "Gran Bassa",
    "Gran Gedeh",
    "Gran Kru",
    "Gran Monte del Cabo",
    "Lofa",
    "Margibi",
    "Maryland",
    "Montserrado",
    "Nimba",
    "Río Gee",
    "Sinoe"
  ],
  "LS": [
    "Berea",
    "Butha-Buthe",
    "Cuello de Qacha",
    "Hoek de Mohale",
    "Leribe",
    "Mafeteng",
    "Maseru",
    "Mokhotlong",
    "Quthing",
    "Thaba-Tseka"
  ],
  "LT": [
    "Akmenė",
    "Alytus",
    "Alytus",
    "Anykščiai",
    "Biržai",
    "Ignalina",
    "Inmersión",
    "Jonava",
    "Joniškis",
    "Jurbarkas",
    "Kaišiadorys",
    "Kaunas",
    "Kaunas",
    "Kėdainiai",
    "Kelmė",
    "Klaipeda",
    "Kretinga",
    "Kupiškis",
    "Lazdijai",
    "Marijampolė",
    "Mažeikiai",
    "Molėtai",
    "Pakruojis",
    "Palanga",
    "Panevėžys",
    "Pasvalys",
    "Prienai",
    "Radviliškis",
    "Raseiniai",
    "Rokiškis",
    "Šakiai",
    "Šalčininkai",
    "Šiauliai",
    "Šiauliai",
    "Šilalė",
    "Šilutė",
    "Širvintos",
    "Skuodas",
    "Švenčionys",
    "Tauragė",
    "Telšiai",
    "Trakai",
    "Ukmergė",
    "Utena",
    "Varėna",
    "Vilkaviškis",
    "Vilna",
    "Vilna",
    "Zarasai"
  ],
  "LU": [
    "Capellen",
    "Clervaux",
    "Diekirch",
    "Echternach",
    "Esch-sur-Alzette",
    "Grevenmacher",
    "Luxemburgo",
    "Mersch",
    "Redange",
    "Remich",
    "Vianden",
    "Wiltz"
  ],
  "LV": [
    "Ādaži",
    "Aizkraukle",
    "Alūksne",
    "Augšdaugava",
    "Balvi",
    "Bauska",
    "Cesis",
    "Dienvidkurzemes",
    "Dobele",
    "Gulbene",
    "Jēkabpils",
    "Jelgava",
    "Ķekava",
    "Kraslava",
    "Kuldiga",
    "Limbaži",
    "Livāni",
    "Ludza",
    "Madona",
    "Mārupe",
    "Ogro",
    "Olaine",
    "Preiļi",
    "Rēzekne",
    "Ropaži",
    "Salaspils",
    "Saldus",
    "Saulkrasti",
    "Sigulda",
    "Smiltene",
    "Talsi",
    "Tukums",
    "Valka",
    "Valmiera",
    "Varakļāni",
    "Ventspils"
  ],
  "LY": [
    "Al Wahat",
    "Bengasi",
    "Derna",
    "Distrito de Al Butnan",
    "Ghat",
    "Jabal al Akhdar",
    "Jabal al Gharbi",
    "Jafara",
    "Jufra",
    "Kufra",
    "Marj",
    "Misrata",
    "Murqub",
    "Murzuq",
    "Nalut",
    "Nuqat al Khams",
    "Sabha",
    "Sirte",
    "Trípoli",
    "Wadi al Hayaa",
    "Wadi al Shatii",
    "Zawiya"
  ],
  "MA": [
    "Al Haouz",
    "Alhucemas",
    "Aousserd (EH)",
    "Assa-Zag (EH-parcial)",
    "Azilal",
    "Beni Melal",
    "Benslimane",
    "Berkan",
    "Berrechid",
    "Bojador (EH)",
    "Boulemane",
    "Chefchaouen",
    "Chichaoua",
    "Chtouka-Ait Baha",
    "Driouch",
    "El Aaiún (EH)",
    "El Hajeb",
    "El Kelâa des Sraghna",
    "El Yadida",
    "Errachidia",
    "Es-Semara (EH-parcial)",
    "Esauira",
    "Fahs-Anjra",
    "Figuig",
    "Fquih Ben Salah",
    "Guelmim",
    "Guercif",
    "Ifrane",
    "Jerada",
    "Juribga",
    "Kenitra",
    "Khémisset",
    "Khénifra",
    "Larache",
    "Médiouna",
    "Midelt",
    "Moulay Yacoub",
    "Nador",
    "Nouaceur",
    "Ouarzazate",
    "Oued Ed-Dahab (EH)",
    "Ouezzane",
    "Rehamna",
    "Safi",
    "Sefrou",
    "Settat",
    "Sidi Bennour",
    "Sidi Ifni",
    "Sidi Kacem",
    "Sidi Slimane",
    "Tan-Tan (EH-parcial)",
    "Taounate",
    "Taourirt",
    "Tarfaya (EH-parcial)",
    "Tarudant",
    "Tata",
    "Taza",
    "Tetuán",
    "Tinghir",
    "Tiznit",
    "Yusufía",
    "Zagora"
  ],
  "MC": [
    "Fontvieille",
    "Jardín Exótico",
    "La Colle",
    "La Condamine",
    "La Gare",
    "La Source",
    "Larvotto",
    "Malbousquet",
    "Mónaco-Ville",
    "Moneghetti",
    "Montecarlo",
    "Moulins",
    "Puerto Hércules",
    "Saint-Roman",
    "Sainte-Dévote",
    "Spélugues",
    "Vallon de la Rousse"
  ],
  "MD": [
    "Anenii Noi",
    "Basarabeasca",
    "Briceni",
    "Cahul",
    "Călărași",
    "Cantante",
    "Cantemir",
    "Căușeni",
    "Cimișlia",
    "Criuleni",
    "Distrito de Leova",
    "Dondușeni",
    "Drochia",
    "Dubăsari",
    "Edineț",
    "Fălești",
    "Florești",
    "Glodeni",
    "Hîncești",
    "Ialoveni",
    "Nisporeni",
    "Ocnița",
    "Orhei",
    "Rezina",
    "Rîșcani",
    "Șoldănești",
    "Soroca",
    "Stefan Vodă",
    "Strășeni",
    "Taraclia",
    "Telenești",
    "Ungheni"
  ],
  "ME": [
    "Andrijevica",
    "Antigua capital real Cetinje",
    "Bar",
    "Berane",
    "Bijelo Polje",
    "Budva",
    "Colašin",
    "Danilovgrad",
    "Gusinje",
    "Herceg Novi",
    "Kotor",
    "Mojkovac",
    "Nikšić",
    "Petnjica",
    "Plav",
    "Pljevlja",
    "Plužine",
    "Podgorica",
    "Rožaje",
    "Šavnik",
    "Tivat",
    "Tuzi",
    "Ulcinj",
    "Žabljak",
    "Ζ"
  ],
  "MF": [
    "Saint-Martin"
  ],
  "MG": [
    "Antananarivo",
    "Antsiranana",
    "Fianarantsoa",
    "Mahajanga",
    "Toamasina",
    "Toliara"
  ],
  "MH": [
    "Ailinglaplap",
    "Ailuk",
    "Arno",
    "AUR (desambiguación)",
    "Bikini y Kili",
    "De ébano",
    "Enewetak y Ujelang",
    "Jabat",
    "Jaluit",
    "Kwajalein",
    "Lae",
    "Lib",
    "Likiep",
    "Majuro",
    "Maloelap",
    "Mejit",
    "Mili (desambiguación)",
    "Namorik",
    "Namu",
    "Rongelap",
    "Ujae",
    "Utirik",
    "Wotho",
    "Wotje"
  ],
  "MK": [
    "Aeródromo",
    "Aračinovo",
    "Berovo",
    "Bitola",
    "Bogdanci",
    "Bogovinje",
    "Bosilovo",
    "Brvenica",
    "Butel",
    "Čair",
    "Čaška",
    "Centar",
    "Centar Župa",
    "Češinovo-Obleševo",
    "Čučer-Sandevo",
    "Debarca",
    "Delčevo",
    "Demir Hisar",
    "Demir Kapija",
    "Dojran",
    "Dolneni",
    "Estudiantes",
    "Excluir",
    "Gazi Baba",
    "Gevgelija",
    "Gjorče Petrov",
    "Gostivar",
    "Gradsko",
    "Ilinden",
    "Jegunovce",
    "Karbinci",
    "Karpoš",
    "Kavadarci",
    "Kičevo",
    "Kisela Voda",
    "Kočani",
    "Konče",
    "Kratovo",
    "Kriva Palanka",
    "Krivogaštani",
    "Kruševo",
    "Kumanovo",
    "Lipkovo",
    "Lozovo",
    "Makedonska Kamenica",
    "Makedonski Brod",
    "Mavrovo y Rostuša",
    "Mogila",
    "Negotino",
    "Novaci",
    "Novo Selo",
    "Ohrid",
    "Pehčevo",
    "Petrovec",
    "Plasnica",
    "Prilep",
    "Probištip",
    "Punta",
    "Radoviš",
    "Rankovce",
    "Reenviar",
    "Rosoman",
    "Saraj",
    "Sopište",
    "Staro Nagoričane",
    "Struga",
    "Strumica",
    "Šuto Orizari",
    "Sveti Nikole",
    "Tearce",
    "Tetovo",
    "Valandovo",
    "Vasilevo",
    "Veles",
    "Vevčani",
    "Vínica",
    "Vrapčište",
    "Zelenikovo",
    "Želino",
    "Zrnovci"
  ],
  "ML": [
    "Gao",
    "Kayes",
    "Kidal",
    "Koulikoro",
    "Ménaka",
    "Mopti",
    "Ségú",
    "Sikasso",
    "Taoudénit",
    "Tombuctú"
  ],
  "MM": [
    "Ayeyarwady",
    "Bago",
    "Magway",
    "Mandalay",
    "Sagaing",
    "Tanintharyi",
    "Yangón"
  ],
  "MN": [
    "Arkhangai",
    "Bayan-Ölgii",
    "Bayankhongor",
    "Bulgan",
    "Darkhan-Uul",
    "Dornod",
    "Dornogovi",
    "Dundgovi",
    "Govi-Altai",
    "Govisümber",
    "Khentii",
    "Khovd",
    "Khövsgöl",
    "Ömnögovi",
    "Orjón",
    "Övörkhangai",
    "rayos ultravioleta",
    "Selenge",
    "Sukhbaatar",
    "Töv",
    "Zavkhan"
  ],
  "MQ": [
    "Fort-de-France",
    "La Trinidad",
    "Le Marin",
    "San Pedro"
  ],
  "MR": [
    "Adrar",
    "Assaba",
    "Brakna",
    "Dakhlet Nuadibú",
    "Górgol",
    "Guidimaka",
    "Hodh Ech Chargui",
    "Hodh El Gharbi",
    "Inchiri",
    "Nouakchott-Nord",
    "Nouakchott-Ouest",
    "Nouakchott-Sud",
    "Tagant",
    "Tiris Zemmour",
    "Trarza"
  ],
  "MS": [
    "San Antonio",
    "San Jorge",
    "San Pedro"
  ],
  "MT": [
    "Attard",
    "Bahía de San Pablo",
    "Balzan",
    "Birgu",
    "Birkirkara",
    "Birżebbuġa",
    "Cospicua",
    "Dingli",
    "Figura",
    "Floriana",
    "Fontana",
    "Għajnsielem",
    "Gharb",
    "Gharghur",
    "Ghasri",
    "Ghaxaq",
    "Gudja",
    "Gzira",
    "Hamrun",
    "Iklin",
    "Kalkara",
    "Kerċem",
    "Kirkop",
    "La Valeta",
    "Lija",
    "Luqa",
    "Marsa",
    "Marsaskala",
    "Marsaxlokk",
    "Medina",
    "Mellieha",
    "Mġarr",
    "Mosta",
    "Mqabba",
    "Msida",
    "Mtarfa",
    "Munxar",
    "Nadur",
    "Naxxar",
    "Paola",
    "Pembroke",
    "Piedad",
    "Qala",
    "Qormi",
    "Qrendi",
    "Rabat",
    "Safi",
    "San Ġwann",
    "San Julián",
    "San Lorenzo",
    "Sannat",
    "Santa Lucía",
    "Santa Venera",
    "Senglea",
    "Siġġiewi",
    "Sliema",
    "Swieqi",
    "Ta' Xbiex",
    "Tarxien",
    "Victoria",
    "Xaghra",
    "Xewkija",
    "Xgħajra",
    "Żabbar",
    "Żebbuġ Gozo",
    "Żebbuġ Malta",
    "Żejtun",
    "Żurrieq"
  ],
  "MU": [
    "Flacq",
    "Gran Puerto",
    "Moka",
    "Pamplemousses",
    "Plaines Wilhems",
    "Puerto Luis",
    "Río del Rempart",
    "Río Negro",
    "Sabana"
  ],
  "MV": [
    "Alif Alif",
    "Alif Dhaal",
    "Atolón Baa",
    "Dhaalu",
    "Faafu",
    "Gaafu Alif",
    "Gaafu Dhaalu",
    "Gnaviyani",
    "Haa Alif",
    "Haa Dhaalu",
    "Kaafu",
    "Laamu",
    "Lhaviyani",
    "Masculino",
    "Mediodía",
    "Meemu",
    "Raa",
    "Shaviyani",
    "Thaa",
    "Vaavu"
  ],
  "MW": [
    "Bahía de Nkhata",
    "Balaka",
    "Blantyre",
    "Chikwawa",
    "Chiradzulú",
    "Chitipa",
    "Dedza",
    "Dowa",
    "Karonga",
    "Kasungu",
    "Likoma",
    "Lilongüe",
    "Machinga",
    "Mangochi",
    "Mchinji",
    "Mulanje",
    "Mwanza",
    "Mzimba",
    "Neno",
    "Nkhotakota",
    "Nsanje",
    "Ntcheu",
    "Ntchisi",
    "Phalombe",
    "Rumphi",
    "Salima",
    "Tiolo",
    "Zomba"
  ],
  "MX": [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila de Zaragoza",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "México",
    "Michoacán de Ocampo",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "salsa Tabasco",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz de Ignacio de la Llave",
    "Yucatán",
    "Zacatecas"
  ],
  "MY": [
    "Johor",
    "Kedah",
    "Kelantan",
    "Malaca",
    "Negeri Sembilan",
    "Pahang",
    "Penang",
    "Perak",
    "Perlis",
    "Sabah",
    "Sarawak",
    "Selangor",
    "Terengganu"
  ],
  "MZ": [
    "Cabo Delgado",
    "Gaza",
    "Inhambane",
    "Manica",
    "Maputo",
    "Nampula",
    "Niassa",
    "Sofala",
    "Tete",
    "Zambezia"
  ],
  "NA": [
    "Erongo",
    "Hardap",
    "Karas",
    "Kavango Este",
    "Kavango Oeste",
    "Khomas",
    "Kunene",
    "Ohangwena",
    "Omaheke",
    "Omusati",
    "Oshana",
    "Oshikoto",
    "Otjozondjupa",
    "Zambeze"
  ],
  "NC": [
    "Provincia de las Islas de la Lealtad",
    "Provincia del Norte",
    "Provincia Sur"
  ],
  "NE": [
    "Agadez",
    "Diffa",
    "Dosso",
    "Maradi",
    "Tahoua",
    "Tillabéri",
    "Zinder"
  ],
  "NG": [
    "Abia",
    "Adamawa",
    "Akwa Ibom",
    "Anambra",
    "Bauchi",
    "Bayelsa",
    "Benue",
    "Borno",
    "Delta",
    "Ebonyi",
    "Edo",
    "Ekiti",
    "Enugu",
    "Gombe",
    "Jigawa",
    "Kaduna",
    "Kano",
    "Katsina",
    "Kebbi",
    "Kogi",
    "Kwara",
    "Lagos",
    "Meseta",
    "Nasarawa",
    "Níger",
    "Ogún",
    "Omi",
    "Ondo",
    "Osun",
    "Oyo",
    "Río Cross",
    "Ríos",
    "Sokoto",
    "Taraba",
    "Yobe",
    "Zamfara"
  ],
  "NI": [
    "Boaco",
    "Carazo",
    "Chinandega",
    "Chontales",
    "Estelí",
    "Granada",
    "Jinotega",
    "León",
    "Madriz",
    "Managua",
    "Masaya",
    "Matagalpa",
    "Nueva Segovia",
    "Río San Juan",
    "Rivas"
  ],
  "NL": [
    "Brabante Septentrional",
    "Drente",
    "Flevoland",
    "Frisia",
    "Groningen",
    "Güeldres",
    "Holanda Meridional",
    "Holanda Septentrional",
    "Limburgo",
    "Overijssel",
    "Utrech",
    "Zelanda"
  ],
  "NO": [
    "Agder",
    "Akershus",
    "Buskerud",
    "Finnmark",
    "Innlandet",
    "Más og Romsdal",
    "Nordland",
    "Oslo",
    "Pliegue posterior",
    "Rogaland",
    "Telemark",
    "Troms",
    "Trøndelag",
    "Vestfold",
    "Vestland"
  ],
  "NP": [
    "Bagmati",
    "Gandaki",
    "Karnali",
    "Koshi",
    "Lumbini",
    "Madhesh",
    "Sudurpashchim"
  ],
  "NR": [
    "Aiwo",
    "Anabar",
    "Anetan",
    "Anibare",
    "Baiti",
    "Boe",
    "Buada",
    "Denigomodu",
    "Ewa",
    "Ijuw",
    "Meneng",
    "Nibok",
    "Uaboe",
    "Yaren"
  ],
  "NU": [
    "Alofi Norte",
    "Alofi Sur",
    "Avatele",
    "Hakupu",
    "Hikutavake",
    "Lakepa",
    "Liku",
    "Makefu",
    "Mutalau",
    "Namukulu",
    "Tamakautoga",
    "Tú",
    "Tuapa",
    "Vaiea"
  ],
  "NZ": [
    "Auckland",
    "Bahía de Hawke",
    "Bahía de Plenty",
    "Canterbury",
    "Costa Oeste",
    "Gisborne",
    "Manawatu-Wanganui",
    "Marlborough",
    "Nelson",
    "Otago",
    "Región septentrional",
    "Taranaki",
    "Tasmania",
    "Tierra del sur",
    "Waikato",
    "Wellington"
  ],
  "OM": [
    "Ad Dakhiliyah",
    "Ad Dhahirah",
    "Al Batinah Norte",
    "Al Batinah Sur",
    "Al Buraimi",
    "Al Wusta",
    "Ash Sharqiyah Norte",
    "Ash Sharqiyah Sur",
    "Dhofar",
    "Moscatel",
    "Musandam"
  ],
  "PA": [
    "Bocas del Toro",
    "Coclé",
    "Colon",
    "Darién",
    "Herrera",
    "Los Santos",
    "Panamá",
    "Panamá Oeste",
    "Provincia de Chiriquí",
    "Veraguas"
  ],
  "PE": [
    "Amazonas",
    "Áncash",
    "Apurímac",
    "Arequipa",
    "Ayacucho",
    "Cajamarca",
    "Callao",
    "Cuzco",
    "Huancavelica",
    "Huánuco",
    "Ica",
    "Junín",
    "La Libertad",
    "Lambayeque",
    "Lima",
    "Loreto",
    "Madre de Dios",
    "Moquegua",
    "Pasco",
    "Piura",
    "Puno",
    "San Martín",
    "Tacna",
    "Tumbes",
    "Ucayali"
  ],
  "PF": [
    "Islas Australes",
    "Islas de Barlovento",
    "Islas de Sotavento",
    "Islas Marquesas",
    "Tuamotu-Gambier"
  ],
  "PG": [
    "Bahía de Milne",
    "Central",
    "Chimbu",
    "Enga",
    "Golfo",
    "Hola",
    "Jiwaka",
    "Madang",
    "Manus",
    "Morobe",
    "Nueva Bretaña Occidental",
    "Nueva Bretaña Oriental",
    "Nueva Irlanda",
    "Occidental",
    "Oro",
    "Sandaun",
    "Sepik Oriental",
    "Tierras altas del sur",
    "Tierras Altas Occidentales",
    "Tierras Altas Orientales"
  ],
  "PH": [
    "Abra",
    "Agusán del Norte",
    "Agusán del Sur",
    "Aklan",
    "Albay",
    "Antigüedad",
    "apayao",
    "Aurora",
    "Basilán",
    "Bataán",
    "Batanes",
    "Batangas",
    "Benguet",
    "Bilirán",
    "Bohol",
    "Bukidnon",
    "Bulacán",
    "Cagayán",
    "Camarines Norte",
    "Camarines Sur",
    "Camiguín",
    "Capiz",
    "Catanduanes",
    "Cavite",
    "Cebú",
    "Cotabato",
    "Cotabato del Sur",
    "Davao de Oro",
    "Davao del Norte",
    "Davao del Sur",
    "Davao Occidental",
    "Davao Oriental",
    "Guimaras",
    "Ifugao",
    "Ilocos Norte",
    "Ilocos Sur",
    "Iloilo",
    "Isabela",
    "Islas Dinagat",
    "Kalinga",
    "La Unión",
    "Laguna",
    "Lanao del Norte",
    "Lanao del Sur",
    "Leyte",
    "Leyte del Sur",
    "Maguindanao del Norte",
    "Maguindanao del Sur",
    "Marinduque",
    "Masbate",
    "Mindoro Occidental",
    "Mindoro Oriental",
    "Misamis Occidental",
    "Misamis Oriental",
    "Negros Occidental",
    "Negros Oriental",
    "Nueva Écija",
    "Nueva Vizcaya",
    "Palawan",
    "Pampanga",
    "Pangasinán",
    "Provincia de la Montaña",
    "Quezón",
    "Quirino",
    "Rizal",
    "Romblón",
    "Samar del Norte",
    "Samar Occidental",
    "Samar Oriental",
    "Sarangani",
    "Siquijor",
    "Sorsogón",
    "Sultán Kudarat",
    "Sulu",
    "Surigao del Norte",
    "Surigao del Sur",
    "Tarlac",
    "Tawi-Tawi",
    "Zambales",
    "Zamboanga del Norte",
    "Zamboanga del Sur",
    "Zamboanga Sibugay"
  ],
  "PK": [
    "Baluchistán",
    "Khyber Pakhtunkhwa",
    "Punjab",
    "Sindh"
  ],
  "PL": [
    "Alta Silesia",
    "Baja Silesia",
    "Cuyavia y Pomerania",
    "Gran Polonia",
    "Lodz",
    "Lublin",
    "Lubusz",
    "Mazovia",
    "Pequeña Polonia",
    "Podlaquia",
    "Pomerania",
    "Pomerania Occidental",
    "Santa Cruz",
    "Silesia",
    "Subcarpatia",
    "Warmia y Masuria"
  ],
  "PM": [
    "Saint-Pierre and Miquelon"
  ],
  "PR": [
    "Adjuntas",
    "Aguada",
    "Aguadilla",
    "Aguas Buenas",
    "Aibonito",
    "Añasco",
    "Barceloneta",
    "Barranquitas",
    "Cabo Rojo",
    "Camuy",
    "Canóvanas",
    "Cataño",
    "Cauce seco de un río",
    "Cayey",
    "Ceiba",
    "Ciales",
    "Cidra",
    "Coamo",
    "Comerío",
    "Corozal",
    "Culebra",
    "Dorado",
    "Fajardo",
    "Florida",
    "Guánica",
    "Guayama",
    "Guayanilla",
    "gurabo",
    "Hatillo",
    "Hormigueros",
    "Humacao",
    "Isabela",
    "Jayuya",
    "Juana Díaz",
    "Juncos",
    "Lajas",
    "Lares",
    "Las Marías",
    "Las Piedras",
    "Loíza",
    "Luquillo",
    "Manatí",
    "Maricao",
    "Maunabo",
    "Moca",
    "Morovis",
    "Naguabo",
    "Naranjito",
    "Orocovis",
    "Patillas",
    "Peñuelas",
    "Quebradillas",
    "Rincón",
    "Río Grande",
    "Sabana Grande",
    "Salinas",
    "San Germán",
    "San Lorenzo",
    "San Sebastián",
    "Santa Isabel",
    "Toa Alta",
    "Utuado",
    "Vega Alta",
    "Vega Baja",
    "Vieques",
    "Villalba",
    "Yabucoa",
    "Yauco"
  ],
  "PS": [
    "Belén",
    "Deir El Balah",
    "Gaza",
    "Hebrón",
    "Jericó",
    "Jerusalén (Quds)",
    "Khan Yunis",
    "Nablus",
    "Norte de Gaza",
    "Qalqilya",
    "Rafah",
    "Ramala",
    "Salfit",
    "Tubas",
    "Tulkarem",
    "Yenín"
  ],
  "PT": [
    "Aveiro",
    "Beja",
    "Braga",
    "Braganza",
    "Castillo Blanco",
    "Coímbra",
    "Évora",
    "Faraón",
    "Guarda",
    "Leiría",
    "Lisboa",
    "Oporto",
    "Portalegre",
    "Santarém",
    "Setúbal",
    "Viana do Castelo",
    "Villa Real",
    "Viseu"
  ],
  "PW": [
    "Aimeliik",
    "Airai",
    "Angaurio",
    "Hatohobei",
    "Kayangel",
    "Koror",
    "Melekeok",
    "Ngaraard",
    "Ngarchelong",
    "Ngardmau",
    "Ngatpang",
    "Ngchesar",
    "Ngeremlengui",
    "Ngiwal",
    "Peleliu",
    "Sonsorol"
  ],
  "PY": [
    "Alto Paraguay",
    "Alto Paraná",
    "Amambay",
    "Asunción",
    "Boquerón",
    "Caaguazú",
    "Caazapá",
    "Canindeyú",
    "Central",
    "Concepción",
    "Cordillera",
    "Guairá",
    "Itapúa",
    "Misiones",
    "Ñeembucú",
    "Paraguarí",
    "Presidente Hayes",
    "San Pedro"
  ],
  "QA": [
    "Al Daayen",
    "Al Jor",
    "Al Rayyan",
    "Al Wakrah",
    "Al-Shahaniya",
    "Doha",
    "Madinat ash Shamal",
    "Umm Salal"
  ],
  "RE": [
    "Saint-Denis",
    "San Benito",
    "San Pablo",
    "San Pedro"
  ],
  "RO": [
    "Alba",
    "Arad",
    "Arges",
    "Bacău",
    "Bihor",
    "Bistrița-Năsăud",
    "Botoşani",
    "Braila",
    "Braşov",
    "Buzău",
    "Călărași",
    "Caraș-Severin",
    "Cluj",
    "Constanza",
    "Covasna",
    "Dâmbovița",
    "Dolj",
    "Galați",
    "Giurgiu",
    "Gorj",
    "Harghita",
    "Hunedoara",
    "Ialomița",
    "Iași",
    "Ilfov",
    "Maramureş",
    "Mehedinți",
    "Mures",
    "Neamț",
    "Olt",
    "Prahova",
    "Salaj",
    "Satu Mare",
    "Sibiu",
    "Suceava",
    "Teleorman",
    "Timiş",
    "Tulcea",
    "Válcea",
    "Vaslui",
    "Vrancea"
  ],
  "RS": [
    "Bačka del Norte",
    "Bačka del Sur",
    "Bačka occidental",
    "Banat del Norte",
    "Banat del Sur",
    "Banato Central",
    "Bor",
    "Braničevo",
    "Jablanica",
    "Kolubara",
    "Kosovo",
    "Kosovo-Pomoravlje",
    "Mačva",
    "Mitrovica (Kosovo)",
    "Moravica",
    "Nišava",
    "Pčinja",
    "Peć",
    "Pirote",
    "Podunavlje",
    "Pomorava",
    "Prizren",
    "Rasina",
    "Raška",
    "Réplica",
    "Srem",
    "Šumadija",
    "Zaječar",
    "Zlatibor"
  ],
  "RU": [
    "Amur",
    "Arcángel",
    "Astracán",
    "Bélgorod",
    "Briansk",
    "Cheliábinsk",
    "Irkutsk",
    "Ivánovo",
    "Kaliningrado",
    "Kaluga",
    "Kémerovo",
    "Kírov",
    "Kostromá",
    "Kurgán",
    "Kursk",
    "Leningrado",
    "Lípetsk",
    "Magadán",
    "Moscú",
    "Múrmansk",
    "Nizhni Nóvgorod",
    "Nóvgorod",
    "Novosibirsk",
    "Óblast de Volgogrado",
    "Omsk",
    "Oremburgo",
    "Oriol",
    "Penza",
    "Pskov",
    "Riazán",
    "Rostov",
    "Sajalín",
    "Samara",
    "Sarátov",
    "Smolensk",
    "Sverdlovsk",
    "Tambov",
    "Tiumén",
    "Tomsk",
    "Tula",
    "Tver",
    "Uliánovsk",
    "Vladimir",
    "Vólogda",
    "Vorónezh",
    "Yaroslavl"
  ],
  "RW": [
    "Del norte",
    "Del sur",
    "Occidental",
    "Oriental"
  ],
  "SA": [
    "Al Bahah",
    "Al Jawf",
    "Al-Qassim",
    "Asir",
    "Fronteras del Norte",
    "Granizo",
    "Jizan",
    "La Meca",
    "Medina",
    "Najrán",
    "Provincia Oriental",
    "Riad",
    "Tabuk"
  ],
  "SB": [
    "Central",
    "Elección",
    "Guadalcanal",
    "Isabel",
    "Makira-Ulawa",
    "Malaita",
    "Occidental",
    "Rennell y Bellona",
    "Temotu"
  ],
  "SC": [
    "Anse Boileau",
    "Anse Royale",
    "Anse-aux-Pins",
    "Au Cap",
    "Bahía Lazare",
    "Bahía Santa Ana",
    "Beau Vallon",
    "Bel Air",
    "Bel Ombre",
    "Caimán de Roche",
    "Cascada",
    "Distrito de Anse Etoile",
    "Glacis",
    "Grand'Anse Mahé",
    "Grand'Anse Praslin",
    "La Digue",
    "La Perseverancia I",
    "La Perseverancia II",
    "La Rivière Anglaise",
    "Los Mamelles",
    "Mont Buxton",
    "Mont Fleuri",
    "Plaisance",
    "Puerto Glaud",
    "Punta La Rue",
    "San Luis",
    "Takamaka"
  ],
  "SD": [
    "Al Jazirah",
    "Al Qadarif",
    "Darfur central",
    "Darfur del Norte",
    "Darfur del Sur",
    "Darfur Occidental",
    "Darfur Oriental",
    "Del norte",
    "Jartum",
    "Kassala",
    "Kordofán del Norte",
    "Kordofán del Sur",
    "Kordofán Occidental",
    "Mar Rojo",
    "Nilo Azul",
    "Nilo Blanco",
    "Río Nilo",
    "Sennar"
  ],
  "SE": [
    "Blekinge",
    "Dalarna",
    "Escania",
    "Estocolmo",
    "Gävleborg",
    "Gotland",
    "Halland",
    "Jämtland",
    "Jönköping",
    "Kalmar",
    "Kronoberg",
    "Norrbotten",
    "Örebro",
    "Östergötland",
    "Södermanland",
    "Uppsala",
    "Värmland",
    "Västerbotten",
    "Västernorrland",
    "Västmanland",
    "Västra Götaland"
  ],
  "SG": [
    "Noreste",
    "Noroeste",
    "Singapur central",
    "Sureste",
    "Suroeste"
  ],
  "SH": [
    "Alarma Forest",
    "Bahía Sandy",
    "Colina azul",
    "Jamestown",
    "Levelwood",
    "Longwood",
    "Medio árbol hueco",
    "San Pablo"
  ],
  "SI": [
    "Ajdovščina",
    "Almacenar",
    "Ankaran",
    "Ardid",
    "Beltinci",
    "Benedicto",
    "Bistrica eslovaca",
    "Bistrica ob Sotli",
    "Bohinj",
    "Borovnica",
    "Bovec",
    "Braslovče",
    "Brda",
    "Brežice",
    "Brezovica",
    "Cankova",
    "Cerklje na Gorenjskem",
    "Cerknica",
    "Cerkno",
    "Cerkvenjak",
    "Cirkulane",
    "Črenšovci",
    "Črna na Koroškem",
    "Črnomelj",
    "Destrnik",
    "Divača",
    "Dobje",
    "Dobrepolje",
    "Dobrna",
    "Dobrovnik",
    "Dol pri Ljubljani",
    "Dolenjske Toplice",
    "Dolina de Loška",
    "Domžale",
    "Dornava",
    "Dravograd",
    "Duplek",
    "Estrellas",
    "Gorenja Vas–Poljane",
    "Gorišnica",
    "Gorje",
    "Gornja Radgona",
    "Gornji Grad",
    "Gornji Petrovci",
    "Grado Dobrova–Polhov",
    "Graduado",
    "Grupos",
    "Hajdina",
    "Hoče–Slivnica",
    "Hodoš",
    "Horjul",
    "Hrastnik",
    "Hrpelje–Kozina",
    "Idrija",
    "Ilirska Bistrica",
    "Ivančna Gorica",
    "Izola",
    "Jesenice",
    "Jezersko",
    "Juršinci",
    "Kamnik",
    "Kanal ob Soči",
    "Kidričevo",
    "Kobarid",
    "Kobilje",
    "Kočevje",
    "Komen",
    "Komenda",
    "Konjice esloveno",
    "Kostanjevica na Krki",
    "Kostel",
    "Kozje",
    "Kranjska Gora",
    "Križevci",
    "Kungota",
    "Kuzmá",
    "Laško",
    "Lenart",
    "Lendava",
    "Litija",
    "Liubliana",
    "Ljutomer",
    "Logatec",
    "Loški Potok",
    "Lovrenc na Pohorju",
    "Luče",
    "Lukovica",
    "Majšperk",
    "Makole",
    "Markovci",
    "Medvode",
    "Mengeš",
    "Metlika",
    "Mežica",
    "Miklavž na Dravskem Polju",
    "Miren–Kostanjevica",
    "Mirna",
    "Mirna Peč",
    "Mislinja",
    "Mokronog–Trebelno",
    "Moravče",
    "Moravske Toplice",
    "Mozirje",
    "Muta",
    "Naklo",
    "Nazaret",
    "Odranci",
    "Oplotnica",
    "Ormož",
    "Osilnica",
    "Pesnica",
    "Pirán",
    "Pivka",
    "Podčetrtek",
    "Podlehnik",
    "Podvelka",
    "Poljčane",
    "Polzela",
    "Postoina",
    "Preddvor",
    "Prenegrita",
    "Prevalje",
    "Puconcí",
    "Rače–Fram",
    "Radeče",
    "Radenci",
    "Radlje ob Dravi",
    "Radovljica",
    "Rápidamente",
    "Ravne na Koroškem",
    "Razkrižje",
    "Rečica ob Savinji",
    "Renče–Vogrsko",
    "Ribnica",
    "Ribnica na Pohorju",
    "Rogaška Slatina",
    "Rogašovci",
    "Rogatec",
    "Šalovci",
    "Sangrado",
    "Selnica ob Dravi",
    "Semič",
    "Šempeter–Vrtojba",
    "Šenčur",
    "Šentilj",
    "Šentjernej",
    "Šentjur",
    "Šentrupert",
    "Sevnica",
    "Sežana",
    "Škocjan",
    "Škofja Loka",
    "Škofljica",
    "Šmarje pri Jelšah",
    "Šmarješke Toplice",
    "Sodražica",
    "Solčava",
    "Šoštanj",
    "Središče ob Dravi",
    "Šsmartno ob Paki",
    "Šsmartno pri Litiji",
    "Straža",
    "Sveta Ana",
    "Sveta Trojica contra Slovenskih Goricah",
    "Sveti Andraž contra Slovenskih Goricah",
    "Sveti Jurij contra Slovenskih Goricah",
    "Sveti Jurij ob Ščavnici",
    "Sveti Tomaž",
    "Tabor",
    "Tipo de",
    "Tišina",
    "Tolmin",
    "Trbovlje",
    "Trebnje",
    "Trnovska Vas",
    "Tronco–Dragomer",
    "Tržič",
    "Trzin",
    "Turnišče",
    "Velika Polana",
    "Velike Lašče",
    "Veržej",
    "Vídeo",
    "Vipava",
    "Vitanje",
    "Vodice",
    "Vojnik",
    "Vransko",
    "Vrhnika",
    "Vuzenica",
    "Yo",
    "Zagorje ob Savi",
    "Žalec",
    "Zavrč",
    "Železniki",
    "Žetale",
    "Žiri",
    "Žirovnica",
    "Zreče",
    "Žužemberk"
  ],
  "SK": [
    "Banská Bystrica",
    "Bratislava",
    "Košice",
    "Nitra",
    "Prešov",
    "Trenčín",
    "Trnava",
    "Žilina"
  ],
  "SL": [
    "Del norte",
    "Del sur",
    "Oriental",
    "Provincia del Noroeste"
  ],
  "SM": [
    "Acquaviva",
    "Borgo Maggiore",
    "Chiesanuova",
    "Domagnano",
    "Faetano",
    "Fiorentino",
    "Montegiardino",
    "San Marino",
    "Serravalle"
  ],
  "SN": [
    "Dakar",
    "Fatick",
    "Kaffrine",
    "Kaolack",
    "Kédougou",
    "Kolda",
    "Louga",
    "Matam",
    "Región de Diourbel",
    "Región de Tambacounda",
    "Región de Thiès",
    "San Luis",
    "Sédhiou",
    "Ziguinchor"
  ],
  "SO": [
    "Awdal",
    "Bahía",
    "Baja Shebelle",
    "Bakool",
    "Banaadir",
    "Bari",
    "Galguduud",
    "Gedo",
    "Hiran",
    "Juba inferior",
    "Juba Medio",
    "Juntos",
    "Mudug",
    "Nugal",
    "Sanaag",
    "Shebelle media",
    "Sool",
    "Woqooyi Galbeed"
  ],
  "SR": [
    "Brokopondo",
    "Commewijne",
    "Coronie",
    "Marowijne",
    "Nickerie",
    "Paraca",
    "Paramaribo",
    "Saramacca",
    "Sipaliwini",
    "Wanica"
  ],
  "SS": [
    "Alto Nilo",
    "Bahr el Ghazal del Norte",
    "Bahr el Ghazal Occidental",
    "Ecuatoria Central",
    "Ecuatoria Occidental",
    "Ecuatoria Oriental",
    "Jonglei",
    "Lagos",
    "Unidad",
    "Warrap"
  ],
  "ST": [
    "Cantagalo",
    "Distrito de Água Grande",
    "Distrito de Caué",
    "Distrito de Mé-Zóchi",
    "Lemba",
    "Lobata"
  ],
  "SV": [
    "Ahuachapán",
    "Cabañas",
    "Chalatenango",
    "Cuscatlán",
    "La Libertad",
    "La Paz",
    "La Unión",
    "Morazán",
    "San Miguel",
    "San Salvador",
    "San Vicente",
    "Santa Ana",
    "Sonsonate",
    "Usulután"
  ],
  "SY": [
    "Al-Hasakah",
    "Al-Raqqa",
    "Alepo",
    "As-Suwayda",
    "Damasco",
    "Damasco Rural",
    "Daraa",
    "Deir ez-Zor",
    "Hama",
    "Homs",
    "Idlib",
    "Latakia",
    "Quneitra",
    "Tartus"
  ],
  "SZ": [
    "Jajaja",
    "Lubombo",
    "Manzini",
    "Shiselweni"
  ],
  "TC": [
    "Caicos centrales",
    "Caicos del Norte",
    "Caicos del Sur",
    "Cayo Salado",
    "Gran Turco",
    "Providenciales"
  ],
  "TD": [
    "Bahr el Gazel",
    "Batha",
    "Borkou",
    "Chari-Baguirmi",
    "Ennedi Oeste",
    "Ennedi-Est",
    "Guera",
    "Hadjer-Lamis",
    "Kanem",
    "Laca",
    "Logone Occidental",
    "Logone Oriental",
    "Mandoul",
    "Mayo-Kebbi Est",
    "Mayo-Kebbi Oeste",
    "Medio Chari",
    "Ouaddaï",
    "Salamat",
    "Sila",
    "Tandjilé",
    "Tibesti",
    "Wadi Fira",
    "Yamena"
  ],
  "TF": [
    "Adélie Land",
    "Crozet Islands",
    "Kerguelen Islands",
    "Saint-Paul and Amsterdam Islands",
    "Scattered Islands"
  ],
  "TG": [
    "Central",
    "Kara",
    "Marítimo",
    "Mesetas",
    "Sabanas"
  ],
  "TH": [
    "Amnat Charoen",
    "Ang Thong",
    "Bueng Kan",
    "Buri Ram",
    "Canta Buri",
    "Chachoengsao",
    "Chai Nat",
    "Chaiyaphum",
    "Chanthaburi",
    "Chiang Mai",
    "Chiang Rai",
    "Chon Buri",
    "Chumphon",
    "Frase",
    "Kalasin",
    "Kamphaeng Phet",
    "Kanchanaburi",
    "Khon Kaen",
    "Krabi",
    "Lampang",
    "Lamphun",
    "Loei",
    "Lop Buri",
    "Mae Hong Son",
    "Maha Sarakham",
    "Mukdahan",
    "Nakhon Nayok",
    "Nakhon Pathom",
    "Nakhon Phanom",
    "Nakhon Ratchasima",
    "Nakhon Sawan",
    "Nakhon Si Thammarat",
    "Narathiwat",
    "Nong Bua Lam Phu",
    "Nong Khai",
    "Nonthaburi",
    "Pathum Thani",
    "Pattani",
    "Phangnga",
    "Phatthalung",
    "Phayao",
    "Phetchabun",
    "Phetchaburi",
    "Phichit",
    "Phitsanulok",
    "Phra Nakhon Si Ayutthaya",
    "Phuket",
    "Prachin Buri",
    "Prachuap Khiri Khan",
    "Ranong",
    "Ratchaburi",
    "Rayong",
    "Rey y",
    "Sa Kaeo",
    "Sakon Nakhon",
    "Samut Prakan",
    "Samut Sakhon",
    "Samut Songkhram",
    "Saraburi",
    "Saturno",
    "Si Sa Ket",
    "Songkhla",
    "Sukhothai",
    "Suphan Buri",
    "Surat Thani",
    "Surin",
    "Toma",
    "Trang",
    "Trato",
    "Ubon Ratchathani",
    "Udon Thani",
    "Uthai Thani",
    "Uttaradit",
    "Yala",
    "Yasotón",
    "Yaya"
  ],
  "TJ": [
    "Khatlon",
    "Sugerido"
  ],
  "TL": [
    "Aileu",
    "Ainaro",
    "Baucau",
    "Bobonaro",
    "Cova Lima",
    "Dili",
    "Ermera",
    "Lautém",
    "Liquiçá",
    "Manatuto",
    "Manufahi",
    "Viqueque"
  ],
  "TM": [
    "Ahal",
    "balcánico",
    "Daşoguz",
    "Lebap",
    "María"
  ],
  "TN": [
    "Ariana",
    "Béja",
    "Ben Arous",
    "Bizerta",
    "Gabés",
    "Gafsa",
    "Jendouba",
    "Kairuán",
    "Kasserine",
    "Kebili",
    "Kef",
    "Mahdia",
    "Manouba",
    "Medenine",
    "Monastir",
    "Nabeul",
    "Sfax",
    "Sidi Bouzid",
    "Siliana",
    "Susa",
    "Tataouine",
    "Tozeur",
    "Túnez",
    "Zaghouan"
  ],
  "TO": [
    "'Eua",
    "Haʻapai",
    "Niuas",
    "Tongatapu",
    "Vavaʻu"
  ],
  "TR": [
    "Adana",
    "Adiyaman",
    "Afyonkarahisar",
    "Agri",
    "Aksaray",
    "Amasya",
    "Ankara",
    "Antalya",
    "Ardahan",
    "Artvin",
    "Aydin",
    "Balikesir",
    "Bartín",
    "Bayburt",
    "Bilecik",
    "Bingöl",
    "Bitlis",
    "Bolsa",
    "Bolu",
    "Burdur",
    "Çanakkale",
    "Çankırı",
    "Çorum",
    "Denizli",
    "Diyarbakir",
    "Düzce",
    "Edirne",
    "Elazığ",
    "Erzincan",
    "Erzurum",
    "Eskişehir",
    "Esmirna",
    "Estanbul",
    "Furgoneta",
    "Gaziantep",
    "Giresun",
    "Gümüşhane",
    "Hakkâri",
    "Hatay",
    "Iğdır",
    "Isparta",
    "Kahramanmaraş",
    "Karabük",
    "Karaman",
    "Kars",
    "Kastamonu",
    "Kayseri",
    "Kilis",
    "Kirikkale",
    "Kirsehir",
    "Kırklareli",
    "Kocaeli",
    "Konya",
    "Kütahya",
    "Malatya",
    "Manisa",
    "Mardin",
    "Mersin",
    "Muğla",
    "Mus",
    "Nevsehir",
    "Niğde",
    "Ordenanza",
    "Ordu",
    "Osmaniye",
    "Rize",
    "Sakarya",
    "Samsun",
    "Sanliurfa",
    "Siirt",
    "Sinop",
    "Sirnak",
    "Sivas",
    "Tekirdağ",
    "Tokat",
    "Trabzon",
    "Tunceli",
    "Usak",
    "Yalova",
    "Yozgat",
    "Zonguldak"
  ],
  "TT": [
    "Couva-Tabaquite-Talparo",
    "Diego Martín",
    "Penal-Debe",
    "Princes Town",
    "Río Claro-Mayaro",
    "San Fernando",
    "San Juan-Laventille",
    "Sangre Grande",
    "Siparia",
    "Tobago occidental",
    "Tobago Oriental",
    "Tunapuna-Piarco"
  ],
  "TV": [
    "Consejo de la isla de Niutao",
    "Nanumanga",
    "Nanumea",
    "Nui",
    "Nukufetau",
    "Nukulaelae",
    "Vaitupu"
  ],
  "TW": [
    "Changhua",
    "Condado de Chiayi",
    "Condado de Hsinchu",
    "Hualién",
    "Lienchiang",
    "Miaoli",
    "Nantou",
    "Parientes",
    "Penghu",
    "Pingtung",
    "Taitung",
    "Yilan",
    "Yunlin"
  ],
  "TZ": [
    "Arusha",
    "Dar es Salaam",
    "Dodoma",
    "Geita",
    "Iringa",
    "Kagera",
    "Katavi",
    "Kigoma",
    "Kilimanjaro",
    "Lindi",
    "Manyara",
    "Mara",
    "Mbeya",
    "Morogoro",
    "Mtwara",
    "Mwanza",
    "Njombe",
    "Norte de Zanzíbar",
    "Pemba Norte",
    "Pemba Sur",
    "Pwani",
    "Rukwa",
    "Ruvuma",
    "Shinyanga",
    "simiyu",
    "Singida",
    "Songwe",
    "Tabora",
    "Tanga",
    "Zanzíbar Oeste",
    "Zanzíbar Sur"
  ],
  "UA": [
    "Cherkaska",
    "Chernigovska",
    "Chernivetska",
    "Dnipropetrovsk",
    "Donetska",
    "Ivano-Frankivska",
    "Járkov",
    "Jersón",
    "Jmelnitska",
    "Kiev",
    "Kirovohradska",
    "Luhanska",
    "Lvivska",
    "Nikolaevska",
    "Odeska",
    "Poltava",
    "Rivnenska",
    "Sumska",
    "Ternopilska",
    "Vínnytska",
    "Volynska",
    "Zakarpatia",
    "Zaporiyia",
    "Zhitomirska"
  ],
  "UG": [
    "Abim",
    "Adjumani",
    "Agago",
    "Alebtong",
    "Amolatar",
    "Amudat",
    "Amuria",
    "Amuru",
    "Arua",
    "Asia Pacífico",
    "Budaka",
    "Bududa",
    "Bugiri",
    "Bugweri",
    "Buhweju",
    "Buikwe",
    "Bukedea",
    "Bukomansimbi",
    "Bukwo",
    "Bulambuli",
    "Buliisa",
    "Bundibugyo",
    "Bunyangabu",
    "Bushenyi",
    "Busia",
    "Butaleja",
    "Butambala",
    "Butebo",
    "Buvuma",
    "Buyende",
    "Col",
    "Dokolo",
    "Gomba",
    "Gulu",
    "Hoima",
    "Ibanda",
    "Iganga",
    "Isingiro",
    "Jinja",
    "Kaabong",
    "Kabale",
    "Kabarole",
    "Kaberamaido",
    "Kagadi",
    "Kakumiro",
    "Kalaki",
    "Kalangala",
    "Kaliro",
    "Kalungu",
    "Kamuli",
    "Kamwenge",
    "Kanungu",
    "Kapchorwa",
    "Kapelebyong",
    "Karenga",
    "Kasanda",
    "Kasese",
    "Katakwi",
    "Kayunga",
    "Kazo",
    "Kibaale",
    "Kiboga",
    "Kibuku",
    "Kikuube",
    "Kiruhura",
    "Kiryandongo",
    "Kisoro",
    "Kitagwenda",
    "Kitgum",
    "Koboko",
    "Kotido",
    "Kumi",
    "Kwania",
    "Kween",
    "Kyankwanzi",
    "Kyegegwa",
    "Kyenjojo",
    "Kyotera",
    "Lamwo",
    "Lira",
    "Luuka",
    "Luwero",
    "Lwengo",
    "Lyantonde",
    "Madi-Okollo",
    "Manafwa",
    "Maracha",
    "Masaka",
    "Masindi",
    "mayuge",
    "Mbale",
    "Mbarara",
    "Mitooma",
    "Mityana",
    "Moroto",
    "Moyo",
    "Mpigi",
    "Mubende",
    "Mukono",
    "Nabilatuk",
    "Nakapiripirit",
    "Nakaseke",
    "Nakasongola",
    "Namayingo",
    "Namisindwa",
    "Namutumba",
    "Napak",
    "Nebbi",
    "Ngora",
    "Ntoroko",
    "Ntungamo",
    "Nwoya",
    "Obongi",
    "Omoro",
    "Otuke",
    "Oyam",
    "Pader",
    "Pakwach",
    "Pallisa",
    "Rakai",
    "Rubanda",
    "Rubirizi",
    "Rukiga",
    "Rukungiri",
    "Rwampara",
    "Sembabule",
    "Serere",
    "Sheema",
    "Sironko",
    "Soroti",
    "Tororo",
    "Wakiso",
    "Yumbe",
    "Zombo"
  ],
  "UM": [
    "Arrecife Kingman",
    "Atolón de Palmira",
    "Atolón Johnston",
    "Isla Baker",
    "Isla de Navassa",
    "Isla Howland",
    "Isla Jarvis",
    "Isla Wake",
    "Islas Midway"
  ],
  "US": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Carolina del Norte",
    "Carolina del Sur",
    "Colorado",
    "Connecticut",
    "Dakota del Norte",
    "Dakota del Sur",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawai",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Luisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Misisipí",
    "Misuri",
    "Montana",
    "Nebraska",
    "Nevada",
    "Nueva Jersey",
    "Nueva York",
    "Nuevo Hampshire",
    "Nuevo Méjico",
    "Ohio",
    "Oklahoma",
    "Oregón",
    "Pensilvania",
    "Rhode Island",
    "Tennesse",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Virginia Occidental",
    "Washington",
    "Wisconsin",
    "Wyoming"
  ],
  "UY": [
    "Artigas",
    "Canelones",
    "Cerro Largo",
    "Colonia",
    "Durazno",
    "Flores",
    "Florida",
    "Lavalleja",
    "Maldonado",
    "Montevideo",
    "Paysandú",
    "Río Negro",
    "Rivera",
    "Rocha",
    "Salto",
    "San José",
    "Soriano",
    "Tacuarembó",
    "Treinta y Tres"
  ],
  "UZ": [
    "Andiján",
    "Bujará",
    "Ferganá",
    "Jizzakh",
    "Namangán",
    "Navoiy",
    "Qashqadaryo",
    "Samarcanda",
    "Sirdaryo",
    "Surxondaryo",
    "Taskent",
    "Xorazm"
  ],
  "VC": [
    "Carlota",
    "Granadinas",
    "San Andrés",
    "San David",
    "San Jorge",
    "San Patricio"
  ],
  "VE": [
    "Amazonas",
    "Anzoátegui",
    "Apure",
    "Aragua",
    "Barinas",
    "Bolívar",
    "Carabobo",
    "Cojedes",
    "Delta Amacuro",
    "Guárico",
    "Halcón",
    "La Guaira",
    "Lara",
    "Mérida",
    "Miranda",
    "Monagas",
    "Nueva Esparta",
    "Portuguesa",
    "Sucre",
    "Táchira",
    "Trujillo",
    "Yaracuy",
    "Zulia"
  ],
  "VI": [
    "San Juan",
    "Santa Cruz",
    "Santo Tomás"
  ],
  "VN": [
    "Bac Ninh",
    "Cà Mau",
    "Cao Bang",
    "Đắk Lắk",
    "Điện Biên",
    "Đồng Nai",
    "Đồng Tháp",
    "Gia Lai",
    "Hà Tĩnh",
    "Hải Phòng",
    "Ho Chí Minh",
    "Hưng Yên",
    "Khánh Hòa",
    "Lai Châu",
    "Lâm Đồng",
    "Lạng Sơn",
    "Lao Cai",
    "Nghệ An",
    "Ninh Binh",
    "Phú Thọ",
    "Quảng Ngãi",
    "Quảng Ninh",
    "Quảng Trị",
    "Son La",
    "Tay Ninh",
    "Thái Nguyên",
    "Thanh Hóa",
    "Thừa Thiên-Huế",
    "Tuyen Quang",
    "Un gigante",
    "Vinh Long"
  ],
  "VU": [
    "Malampa",
    "Penama",
    "Sanma",
    "Shefa",
    "Tafea",
    "Torba"
  ],
  "WF": [
    "Alo (desambiguación)",
    "Sigave",
    "Úvea"
  ],
  "WS": [
    "A'ana",
    "Aiga-i-le-Tai",
    "Atua",
    "Fa'asaleleaga",
    "Gaga'emauga",
    "Gaga'ifomauga",
    "Palauli",
    "Satupa'itea",
    "Tuamasaga",
    "Va'a-o-Fonoti",
    "Vaisigano"
  ],
  "XK": [
    "Ferizaj",
    "Gjakove",
    "Gjilan",
    "Mitrovica",
    "Peja",
    "Pristina",
    "Prizren"
  ],
  "YE": [
    "Abyan",
    "Adán",
    "Al Bayda'",
    "Al Dhale",
    "Al Hudaydah",
    "Al Jawf",
    "Al Mahrah",
    "Al Mahwit",
    "Amran",
    "Dhamar",
    "Hadramaut",
    "Hajjah",
    "Ibb",
    "Lahij",
    "Marib",
    "Raymah",
    "Saada",
    "Saná",
    "Shabwah",
    "Socotra",
    "Taizz"
  ],
  "YT": [
    "Acoua",
    "Bandraboua",
    "Bandrélé",
    "Boueni",
    "Chiconi",
    "Chirongui",
    "Dembeni",
    "Dzaoudzi",
    "Kani Keli",
    "Koungou",
    "M'Tsangamouji",
    "Mamoudzou",
    "Mtsamboro",
    "Ouangani",
    "Pamandzi",
    "Sada",
    "Tsingoni"
  ],
  "ZA": [
    "Cabo del Norte",
    "Cabo Occidental",
    "Cabo Oriental",
    "Estado Libre",
    "Gauteng",
    "KwaZulu-Natal",
    "Limpopo",
    "Mpumalanga",
    "Noroeste"
  ],
  "ZM": [
    "Central",
    "Cinturón de cobre",
    "Del norte",
    "Del sur",
    "Luapula",
    "Lusaka",
    "Muchinga",
    "Noroeste",
    "Occidental",
    "Oriental"
  ],
  "ZW": [
    "Bulawayo",
    "Harare",
    "la región central de Inglaterra",
    "Manicaland",
    "Mashonalandia Central",
    "Mashonalandia Occidental",
    "Mashonalandia Oriental",
    "Masvingo",
    "Matabeleland Norte",
    "Matabeleland Sur"
  ]
};
